#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

# ---------------------------------------------------------------
# NOTE
#
# This "script" is NOT meant to be executed directly.
# It is included as a source file by scripts/build_toolchian.
#
# ---------------------------------------------------------------

ubuntu_pkg_list=()
ubuntu_pkg_list+=(wget)
ubuntu_pkg_list+=(git)
ubuntu_pkg_list+=(gcc)
ubuntu_pkg_list+=(g++)
ubuntu_pkg_list+=(make)
ubuntu_pkg_list+=(cmake)
ubuntu_pkg_list+=(binutils)
ubuntu_pkg_list+=(bzip2)
ubuntu_pkg_list+=(rpm2cpio)
ubuntu_pkg_list+=(cpio)
ubuntu_pkg_list+=(qemu-system-x86)

function install_debian_family {

   pkg_list=( "${ubuntu_pkg_list[@]}" )
   to_install=()

   echo Checking the packages that need to be installed

   for x in ${pkg_list[@]}; do
      echo -ne "Checking $x... "

      if [ "`dpkg -s $x 2>&1 | grep Status`" ]; then
         echo OK
      else
         echo NOT found
         to_install+=($x)
      fi
   done

   echo

   if [ ${#to_install[@]} -ne 0 ]; then

      echo ${#to_install[@]} packages need to be installed
      tmp="${to_install[@]}"

      if ! which sudo &> /dev/null; then
         cmd="su -c \"apt install $tmp\""
      else
         cmd="sudo apt install $tmp"
      fi

      echo "Running the command: $cmd"
      eval $cmd

   else
      echo "You are all set, no packages need to be installed."
   fi
}

function install_fedora {

   pkg_list=()
   pkg_list+=(wget)
   pkg_list+=(git)
   pkg_list+=(gcc)
   pkg_list+=(gcc-c++)
   pkg_list+=(make)
   pkg_list+=(cmake)
   pkg_list+=(binutils)
   pkg_list+=(bzip2)
   pkg_list+=(cpio)
   pkg_list+=(qemu-system-x86)

   to_install=()

   echo Checking the packages that need to be installed

   for x in ${pkg_list[@]}; do
      echo -ne "Checking $x... "

      if dnf list installed $x &> /dev/null; then
         echo OK
      else
         echo NOT found
         to_install+=($x)
      fi
   done

   if [ ${#to_install[@]} -ne 0 ]; then
      echo ${#to_install[@]} packages need to be installed
      tmp="${to_install[@]}"
      run_command "sudo dnf install $tmp"
   else
      echo "You are all set, no packages need to be installed."
   fi
}

function install_arch {

   pkg_list=()
   pkg_list+=(wget)
   pkg_list+=(git)
   pkg_list+=(gcc)
   pkg_list+=(make)
   pkg_list+=(cmake)
   pkg_list+=(binutils)
   pkg_list+=(bzip2)
   pkg_list+=(rpmextract)
   pkg_list+=(cpio)
   pkg_list+=(qemu)
   pkg_list+=(qemu-arch-extra)

   to_install=()
   echo Checking the packages that need to be installed

   for x in ${pkg_list[@]}; do
      echo -ne "Checking $x... "

      if pacman -Q $x &> /dev/null; then
         echo OK
      else
         echo NOT found
         to_install+=($x)
      fi
   done

   if [ ${#to_install[@]} -ne 0 ]; then
      echo ${#to_install[@]} packages need to be installed
      tmp="${to_install[@]}"
      run_command "sudo pacman -S $tmp"
   else
      echo "You are all set, no packages need to be installed."
   fi
}

function install_openSUSE {

   pkg_list=()
   pkg_list+=(wget)
   pkg_list+=(git-core)
   pkg_list+=(gcc)
   pkg_list+=(gcc-c++)
   pkg_list+=(make)
   pkg_list+=(cmake)
   pkg_list+=(binutils)
   pkg_list+=(bzip2)
   pkg_list+=(cpio)
   pkg_list+=(qemu-x86)

   to_install=()
   echo Checking the packages that need to be installed

   for x in ${pkg_list[@]}; do
      echo -ne "Checking $x... "

      if rpm -q $x &> /dev/null; then
         echo OK
      else
         echo NOT found
         to_install+=($x)
      fi
   done

   if [ ${#to_install[@]} -ne 0 ]; then
      echo ${#to_install[@]} packages need to be installed
      tmp="${to_install[@]}"
      run_command "sudo zypper install $tmp"
   else
      echo "You are all set, no packages need to be installed."
   fi
}

function install_packages {

   rel_files=`echo /etc/*release`
   lsb="/etc/lsb-release"
   os_rel="/etc/os-release"

   # Where lsb-release exists, use only it.
   # On Mint doing grep /etc/*release reports an error because there is an
   # upstream-release directory matching that wildcard. Using grep -r is not
   # a solution since in /etc/upstream-release/* on Mint, Ubuntu is mentioned.
   if [ -f $lsb ] && [ "$(grep -Ei 'buntu|mint' $lsb)" ]; then

      echo "Distribution detected: Ubuntu (any) or Mint"
      echo ""
      install_debian_family

   # Debian does not contain the lsb-release file.
   elif [ -f $os_rel ] && [ "$(grep -Ei 'debian' $os_rel)" ]; then

      echo "Distribution detected: Debian"
      echo ""
      install_debian_family

   # On Fedora, we need to check if exactly a [Ff]edora-release file exists.
   elif echo $rel_files | grep -Ei 'fedora' - &> /dev/null; then

      echo "Distribution detected: Fedora"
      echo ""
      install_fedora

   elif echo $rel_files | grep -Ei 'arch|manjaro' - &> /dev/null; then

      echo "Distribution detected: Arch or Manjaro"
      echo ""
      install_arch

   elif [ -f $os_rel ] && [ "$(grep -Ei 'openSUSE' $os_rel)" ]; then

      echo "Distribution detected: openSUSE"
      echo ""
      install_openSUSE

   else

      pkg_list=()

      if ! which wget &> /dev/null; then
         pkg_list+=(wget)
      fi

      if ! which git &> /dev/null; then
         pkg_list+=(git)
      fi

      if ! which gcc &> /dev/null; then
         pkg_list+=(gcc)
      fi

      if ! which g++ &> /dev/null; then
         pkg_list+=(g++)
      fi

      if ! which make &> /dev/null; then
         pkg_list+=(make)
      fi

      if ! which cmake &> /dev/null; then
         pkg_list+=(cmake)
      fi

      if ! which objdump &> /dev/null; then
         pkg_list+=(binutils)
      fi

      if ! which rpm2cpio &> /dev/null; then
         pkg_list+=(rpm2cpio)
      fi

      if ! which cpio &> /dev/null; then
         pkg_list+=(cpio)
      fi

      if ! which bzip2 &> /dev/null; then
         pkg_list+=(bzip2)
      fi

      if ! which qemu-system-i386 &> /dev/null; then
         pkg_list+=(qemu-system-x86)
      fi

      if [ ${#pkg_list[@]} -ne 0 ]; then

         echo "Your distribution is not fully supported by this script."
         echo "The supported distros are:"
         echo "  * Ubuntu"
         echo "  * Mint"
         echo "  * Debian"
         echo "  * Fedora"
         echo "  * Arch"
         echo "  * Manjaro"
         echo "  * openSUSE"
         echo "In order to build Tilck on this distro, please make sure the "
         echo "following packages (ubuntu package names) are installed:"

         for x in ${pkg_list[@]}; do
            echo "  * $x"
         done

         echo "After that, re-run this script with --skip-install-pkgs"
         exit 1

      fi
   fi

}
