#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# LCOV (front end for GCOV)
###############################

function download_lcov {

   local tarname="lcov-1.13.tgz"
   local url="https://github.com/linux-test-project/lcov.git"

   download_git_repo_in_cache "$url" v1.13 $tarname lcov
   extract_cachefile_tar_gz $tarname --
}

all_funcs_list+=(build_lcov)
function build_lcov {

   pushd noarch

   if ! [ -d lcov ]; then

      show_work_on_component_msg "LCOV"

      download_lcov
      cd lcov

   else
      show_skip_component_msg "LCOV"
   fi

   popd
}
