#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

all_funcs_list+=(build_zlib)
function build_zlib {

   pushd $ARCH

   if ! [ -d zlib ]; then

      show_work_on_component_msg "ZLIB"
      reset_cc_vars

      git clone --branch v1.2.11 --depth 1 https://github.com/madler/zlib
      cd zlib

      local p="$TC/$ARCH/zlib/install"

      if [[ "$HOST_ARCH" != "$BUILD_ARCH" ]]; then

         # Case HOST_ARCH == ARCH
         # Note: if HOST_ARCH not in [BUILD_ARCH, ARCH], we fail earlier.
         export SYS_CC="$CC"
         export SYS_CXX="$CXX"
         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"

      else

         # Default case
         export CROSS_PREFIX="${ARCH_GCC_TC}-linux-"
         set_cc_vars_to_tc
      fi

      run_command2 "./configure --prefix='$p' --static" configure.log
      run_command2 "make -j" build.log
      run_command2 "make install" install.log
      export CROSS_PREFIX=""

   else
      show_skip_component_msg "ZLIB"
   fi

   popd
}
