#!/bin/bash

CC=gcc-6
CXX=g++-6
CMAKE=../toolchain/cmake-3.7.0-Linux-x86_64/bin/cmake

if [ -z "$RELEASE" ]; then
   # unset, assuming OFF by default
   RELEASE=off
fi

if [ -z "$USE_GCOV" ]; then
   USE_GCOV=off
fi

mkdir -p build
cd build
$CMAKE -D RELEASE_BUILD:BOOL=$RELEASE -D USE_GCOV:BOOL=$USE_GCOV .. $@

