#!/bin/bash

if [ -z "$CC" ]; then
   CC=gcc
fi

if [ -z "$CXX" ]; then
   CXX=g++
fi

sed_ver_regex='s/[A-Za-z0-9+]+[ ].+[ ]([0-9]+[.][0-9]+[.][0-9]+)[ ].*/\1/g'

cc_ver=`$CC --version | head -1 | sed -E "$sed_ver_regex"`
cxx_ver=`$CXX --version | head -1 | sed -E "$sed_ver_regex"`

echo "CC version:  $cc_ver"
echo "CXX version: $cxx_ver"

cc_major=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -1`
cxx_major=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -1`

if [ $cc_major -lt 6 ]; then
   echo "Your GCC compiler is too old. Version >= 6 is required."
   exit 1
fi

if [ $cxx_major -lt 6 ]; then
   echo "Your G++ compiler is too old. Version >= 6 is required."
   exit 1
fi


CMAKE=../toolchain/cmake-3.7.0-Linux-x86_64/bin/cmake

if [ -z "$RELEASE" ]; then
   RELEASE=off
fi

if [ -z "$USE_GCOV" ]; then
   USE_GCOV=off
fi

mkdir -p build
cd build
$CMAKE -D RELEASE_BUILD:BOOL=$RELEASE -D USE_GCOV:BOOL=$USE_GCOV .. $@

