#!/bin/bash

# If USE_GCOV is empty/unset but TRAVIS is set, exit

if [ -z "$USE_GCOV" ]; then
   if [ -n "$TRAVIS" ]; then
      echo "Exit 0 without doing anything"
      exit 0
   fi
fi

cd build
lcov -d . --capture --gcov-tool `which gcov-6` -o lcov.info
lcov --remove lcov.info '*toolchain*' '/usr/include/*' -o lcov2.info
rm -rf coverage
mkdir coverage
genhtml --output-directory coverage lcov2.info
find . -type f -name '*.gcda' -print | xargs /bin/rm -f
rm lcov*.info
