#!/bin/bash

# If USE_GCOV is empty/unset but TRAVIS is set, exit
# In other words, the USE_GCOV controls this script only if it is running
# under TRAVIS, which makes sense.

if [ -z "$USE_GCOV" ]; then
   if [ -n "$TRAVIS" ]; then
      echo "Exit 0 without doing anything"
      exit 0
   fi
fi

LCOV=$PWD/toolchain/lcov/bin/lcov
GENHTML=$PWD/toolchain/lcov/bin/genhtml

cd build
$LCOV -d . --capture --gcov-tool `which gcov-6` -o lcov.info
$LCOV --remove lcov.info '*toolchain*' '/usr/include/*' -o lcov2.info
rm -rf coverage
mkdir coverage
$GENHTML --output-directory coverage lcov2.info
find . -type f -name '*.gcda' -print | xargs /bin/rm -f
rm lcov*.info
