# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/vvaltchev/Desktop/exOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/vvaltchev/Desktop/exOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vvaltchev/Desktop/exOS/CMakeFiles /mnt/c/Users/vvaltchev/Desktop/exOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vvaltchev/Desktop/exOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named elf_kernel

# Build rule for target.
elf_kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elf_kernel
.PHONY : elf_kernel

# fast build rule for target.
elf_kernel/fast:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/build
.PHONY : elf_kernel/fast

kernel/debug_utils.o: kernel/debug_utils.c.o
.PHONY : kernel/debug_utils.o

# target to build an object file
kernel/debug_utils.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/debug_utils.c.o
.PHONY : kernel/debug_utils.c.o

kernel/debug_utils.i: kernel/debug_utils.c.i
.PHONY : kernel/debug_utils.i

# target to preprocess a source file
kernel/debug_utils.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/debug_utils.c.i
.PHONY : kernel/debug_utils.c.i

kernel/debug_utils.s: kernel/debug_utils.c.s
.PHONY : kernel/debug_utils.s

# target to generate assembly for a file
kernel/debug_utils.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/debug_utils.c.s
.PHONY : kernel/debug_utils.c.s

kernel/elf_loader.o: kernel/elf_loader.c.o
.PHONY : kernel/elf_loader.o

# target to build an object file
kernel/elf_loader.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/elf_loader.c.o
.PHONY : kernel/elf_loader.c.o

kernel/elf_loader.i: kernel/elf_loader.c.i
.PHONY : kernel/elf_loader.i

# target to preprocess a source file
kernel/elf_loader.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/elf_loader.c.i
.PHONY : kernel/elf_loader.c.i

kernel/elf_loader.s: kernel/elf_loader.c.s
.PHONY : kernel/elf_loader.s

# target to generate assembly for a file
kernel/elf_loader.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/elf_loader.c.s
.PHONY : kernel/elf_loader.c.s

kernel/i386/gdt.o: kernel/i386/gdt.c.o
.PHONY : kernel/i386/gdt.o

# target to build an object file
kernel/i386/gdt.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/gdt.c.o
.PHONY : kernel/i386/gdt.c.o

kernel/i386/gdt.i: kernel/i386/gdt.c.i
.PHONY : kernel/i386/gdt.i

# target to preprocess a source file
kernel/i386/gdt.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/gdt.c.i
.PHONY : kernel/i386/gdt.c.i

kernel/i386/gdt.s: kernel/i386/gdt.c.s
.PHONY : kernel/i386/gdt.s

# target to generate assembly for a file
kernel/i386/gdt.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/gdt.c.s
.PHONY : kernel/i386/gdt.c.s

kernel/i386/idt.o: kernel/i386/idt.c.o
.PHONY : kernel/i386/idt.o

# target to build an object file
kernel/i386/idt.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/idt.c.o
.PHONY : kernel/i386/idt.c.o

kernel/i386/idt.i: kernel/i386/idt.c.i
.PHONY : kernel/i386/idt.i

# target to preprocess a source file
kernel/i386/idt.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/idt.c.i
.PHONY : kernel/i386/idt.c.i

kernel/i386/idt.s: kernel/i386/idt.c.s
.PHONY : kernel/i386/idt.s

# target to generate assembly for a file
kernel/i386/idt.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/idt.c.s
.PHONY : kernel/i386/idt.c.s

kernel/i386/irq.o: kernel/i386/irq.c.o
.PHONY : kernel/i386/irq.o

# target to build an object file
kernel/i386/irq.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/irq.c.o
.PHONY : kernel/i386/irq.c.o

kernel/i386/irq.i: kernel/i386/irq.c.i
.PHONY : kernel/i386/irq.i

# target to preprocess a source file
kernel/i386/irq.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/irq.c.i
.PHONY : kernel/i386/irq.c.i

kernel/i386/irq.s: kernel/i386/irq.c.s
.PHONY : kernel/i386/irq.s

# target to generate assembly for a file
kernel/i386/irq.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/irq.c.s
.PHONY : kernel/i386/irq.c.s

kernel/i386/kernelAsm.o: kernel/i386/kernelAsm.asm.o
.PHONY : kernel/i386/kernelAsm.o

# target to build an object file
kernel/i386/kernelAsm.asm.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/kernelAsm.asm.o
.PHONY : kernel/i386/kernelAsm.asm.o

kernel/i386/paging.o: kernel/i386/paging.c.o
.PHONY : kernel/i386/paging.o

# target to build an object file
kernel/i386/paging.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/paging.c.o
.PHONY : kernel/i386/paging.c.o

kernel/i386/paging.i: kernel/i386/paging.c.i
.PHONY : kernel/i386/paging.i

# target to preprocess a source file
kernel/i386/paging.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/paging.c.i
.PHONY : kernel/i386/paging.c.i

kernel/i386/paging.s: kernel/i386/paging.c.s
.PHONY : kernel/i386/paging.s

# target to generate assembly for a file
kernel/i386/paging.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/paging.c.s
.PHONY : kernel/i386/paging.c.s

kernel/i386/process32.o: kernel/i386/process32.c.o
.PHONY : kernel/i386/process32.o

# target to build an object file
kernel/i386/process32.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/process32.c.o
.PHONY : kernel/i386/process32.c.o

kernel/i386/process32.i: kernel/i386/process32.c.i
.PHONY : kernel/i386/process32.i

# target to preprocess a source file
kernel/i386/process32.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/process32.c.i
.PHONY : kernel/i386/process32.c.i

kernel/i386/process32.s: kernel/i386/process32.c.s
.PHONY : kernel/i386/process32.s

# target to generate assembly for a file
kernel/i386/process32.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/process32.c.s
.PHONY : kernel/i386/process32.c.s

kernel/i386/utils32.o: kernel/i386/utils32.c.o
.PHONY : kernel/i386/utils32.o

# target to build an object file
kernel/i386/utils32.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/utils32.c.o
.PHONY : kernel/i386/utils32.c.o

kernel/i386/utils32.i: kernel/i386/utils32.c.i
.PHONY : kernel/i386/utils32.i

# target to preprocess a source file
kernel/i386/utils32.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/utils32.c.i
.PHONY : kernel/i386/utils32.c.i

kernel/i386/utils32.s: kernel/i386/utils32.c.s
.PHONY : kernel/i386/utils32.s

# target to generate assembly for a file
kernel/i386/utils32.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/i386/utils32.c.s
.PHONY : kernel/i386/utils32.c.s

kernel/kb.o: kernel/kb.c.o
.PHONY : kernel/kb.o

# target to build an object file
kernel/kb.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kb.c.o
.PHONY : kernel/kb.c.o

kernel/kb.i: kernel/kb.c.i
.PHONY : kernel/kb.i

# target to preprocess a source file
kernel/kb.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kb.c.i
.PHONY : kernel/kb.c.i

kernel/kb.s: kernel/kb.c.s
.PHONY : kernel/kb.s

# target to generate assembly for a file
kernel/kb.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kb.c.s
.PHONY : kernel/kb.c.s

kernel/kmalloc.o: kernel/kmalloc.c.o
.PHONY : kernel/kmalloc.o

# target to build an object file
kernel/kmalloc.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc.c.o
.PHONY : kernel/kmalloc.c.o

kernel/kmalloc.i: kernel/kmalloc.c.i
.PHONY : kernel/kmalloc.i

# target to preprocess a source file
kernel/kmalloc.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc.c.i
.PHONY : kernel/kmalloc.c.i

kernel/kmalloc.s: kernel/kmalloc.c.s
.PHONY : kernel/kmalloc.s

# target to generate assembly for a file
kernel/kmalloc.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc.c.s
.PHONY : kernel/kmalloc.c.s

kernel/kmalloc_util.o: kernel/kmalloc_util.c.o
.PHONY : kernel/kmalloc_util.o

# target to build an object file
kernel/kmalloc_util.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc_util.c.o
.PHONY : kernel/kmalloc_util.c.o

kernel/kmalloc_util.i: kernel/kmalloc_util.c.i
.PHONY : kernel/kmalloc_util.i

# target to preprocess a source file
kernel/kmalloc_util.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc_util.c.i
.PHONY : kernel/kmalloc_util.c.i

kernel/kmalloc_util.s: kernel/kmalloc_util.c.s
.PHONY : kernel/kmalloc_util.s

# target to generate assembly for a file
kernel/kmalloc_util.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/kmalloc_util.c.s
.PHONY : kernel/kmalloc_util.c.s

kernel/main.o: kernel/main.c.o
.PHONY : kernel/main.o

# target to build an object file
kernel/main.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/main.c.o
.PHONY : kernel/main.c.o

kernel/main.i: kernel/main.c.i
.PHONY : kernel/main.i

# target to preprocess a source file
kernel/main.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/main.c.i
.PHONY : kernel/main.c.i

kernel/main.s: kernel/main.c.s
.PHONY : kernel/main.s

# target to generate assembly for a file
kernel/main.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/main.c.s
.PHONY : kernel/main.c.s

kernel/pageframe_allocator.o: kernel/pageframe_allocator.c.o
.PHONY : kernel/pageframe_allocator.o

# target to build an object file
kernel/pageframe_allocator.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/pageframe_allocator.c.o
.PHONY : kernel/pageframe_allocator.c.o

kernel/pageframe_allocator.i: kernel/pageframe_allocator.c.i
.PHONY : kernel/pageframe_allocator.i

# target to preprocess a source file
kernel/pageframe_allocator.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/pageframe_allocator.c.i
.PHONY : kernel/pageframe_allocator.c.i

kernel/pageframe_allocator.s: kernel/pageframe_allocator.c.s
.PHONY : kernel/pageframe_allocator.s

# target to generate assembly for a file
kernel/pageframe_allocator.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/pageframe_allocator.c.s
.PHONY : kernel/pageframe_allocator.c.s

kernel/perftests.o: kernel/perftests.c.o
.PHONY : kernel/perftests.o

# target to build an object file
kernel/perftests.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests.c.o
.PHONY : kernel/perftests.c.o

kernel/perftests.i: kernel/perftests.c.i
.PHONY : kernel/perftests.i

# target to preprocess a source file
kernel/perftests.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests.c.i
.PHONY : kernel/perftests.c.i

kernel/perftests.s: kernel/perftests.c.s
.PHONY : kernel/perftests.s

# target to generate assembly for a file
kernel/perftests.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests.c.s
.PHONY : kernel/perftests.c.s

kernel/perftests_data.o: kernel/perftests_data.c.o
.PHONY : kernel/perftests_data.o

# target to build an object file
kernel/perftests_data.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests_data.c.o
.PHONY : kernel/perftests_data.c.o

kernel/perftests_data.i: kernel/perftests_data.c.i
.PHONY : kernel/perftests_data.i

# target to preprocess a source file
kernel/perftests_data.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests_data.c.i
.PHONY : kernel/perftests_data.c.i

kernel/perftests_data.s: kernel/perftests_data.c.s
.PHONY : kernel/perftests_data.s

# target to generate assembly for a file
kernel/perftests_data.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/perftests_data.c.s
.PHONY : kernel/perftests_data.c.s

kernel/process.o: kernel/process.c.o
.PHONY : kernel/process.o

# target to build an object file
kernel/process.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/process.c.o
.PHONY : kernel/process.c.o

kernel/process.i: kernel/process.c.i
.PHONY : kernel/process.i

# target to preprocess a source file
kernel/process.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/process.c.i
.PHONY : kernel/process.c.i

kernel/process.s: kernel/process.c.s
.PHONY : kernel/process.s

# target to generate assembly for a file
kernel/process.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/process.c.s
.PHONY : kernel/process.c.s

kernel/string_util.o: kernel/string_util.c.o
.PHONY : kernel/string_util.o

# target to build an object file
kernel/string_util.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/string_util.c.o
.PHONY : kernel/string_util.c.o

kernel/string_util.i: kernel/string_util.c.i
.PHONY : kernel/string_util.i

# target to preprocess a source file
kernel/string_util.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/string_util.c.i
.PHONY : kernel/string_util.c.i

kernel/string_util.s: kernel/string_util.c.s
.PHONY : kernel/string_util.s

# target to generate assembly for a file
kernel/string_util.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/string_util.c.s
.PHONY : kernel/string_util.c.s

kernel/syscalls.o: kernel/syscalls.c.o
.PHONY : kernel/syscalls.o

# target to build an object file
kernel/syscalls.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/syscalls.c.o
.PHONY : kernel/syscalls.c.o

kernel/syscalls.i: kernel/syscalls.c.i
.PHONY : kernel/syscalls.i

# target to preprocess a source file
kernel/syscalls.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/syscalls.c.i
.PHONY : kernel/syscalls.c.i

kernel/syscalls.s: kernel/syscalls.c.s
.PHONY : kernel/syscalls.s

# target to generate assembly for a file
kernel/syscalls.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/syscalls.c.s
.PHONY : kernel/syscalls.c.s

kernel/term.o: kernel/term.c.o
.PHONY : kernel/term.o

# target to build an object file
kernel/term.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/term.c.o
.PHONY : kernel/term.c.o

kernel/term.i: kernel/term.c.i
.PHONY : kernel/term.i

# target to preprocess a source file
kernel/term.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/term.c.i
.PHONY : kernel/term.c.i

kernel/term.s: kernel/term.c.s
.PHONY : kernel/term.s

# target to generate assembly for a file
kernel/term.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/term.c.s
.PHONY : kernel/term.c.s

kernel/timer.o: kernel/timer.c.o
.PHONY : kernel/timer.o

# target to build an object file
kernel/timer.c.o:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/timer.c.o
.PHONY : kernel/timer.c.o

kernel/timer.i: kernel/timer.c.i
.PHONY : kernel/timer.i

# target to preprocess a source file
kernel/timer.c.i:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/timer.c.i
.PHONY : kernel/timer.c.i

kernel/timer.s: kernel/timer.c.s
.PHONY : kernel/timer.s

# target to generate assembly for a file
kernel/timer.c.s:
	$(MAKE) -f CMakeFiles/elf_kernel.dir/build.make CMakeFiles/elf_kernel.dir/kernel/timer.c.s
.PHONY : kernel/timer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... elf_kernel"
	@echo "... kernel/debug_utils.o"
	@echo "... kernel/debug_utils.i"
	@echo "... kernel/debug_utils.s"
	@echo "... kernel/elf_loader.o"
	@echo "... kernel/elf_loader.i"
	@echo "... kernel/elf_loader.s"
	@echo "... kernel/i386/gdt.o"
	@echo "... kernel/i386/gdt.i"
	@echo "... kernel/i386/gdt.s"
	@echo "... kernel/i386/idt.o"
	@echo "... kernel/i386/idt.i"
	@echo "... kernel/i386/idt.s"
	@echo "... kernel/i386/irq.o"
	@echo "... kernel/i386/irq.i"
	@echo "... kernel/i386/irq.s"
	@echo "... kernel/i386/kernelAsm.o"
	@echo "... kernel/i386/paging.o"
	@echo "... kernel/i386/paging.i"
	@echo "... kernel/i386/paging.s"
	@echo "... kernel/i386/process32.o"
	@echo "... kernel/i386/process32.i"
	@echo "... kernel/i386/process32.s"
	@echo "... kernel/i386/utils32.o"
	@echo "... kernel/i386/utils32.i"
	@echo "... kernel/i386/utils32.s"
	@echo "... kernel/kb.o"
	@echo "... kernel/kb.i"
	@echo "... kernel/kb.s"
	@echo "... kernel/kmalloc.o"
	@echo "... kernel/kmalloc.i"
	@echo "... kernel/kmalloc.s"
	@echo "... kernel/kmalloc_util.o"
	@echo "... kernel/kmalloc_util.i"
	@echo "... kernel/kmalloc_util.s"
	@echo "... kernel/main.o"
	@echo "... kernel/main.i"
	@echo "... kernel/main.s"
	@echo "... kernel/pageframe_allocator.o"
	@echo "... kernel/pageframe_allocator.i"
	@echo "... kernel/pageframe_allocator.s"
	@echo "... kernel/perftests.o"
	@echo "... kernel/perftests.i"
	@echo "... kernel/perftests.s"
	@echo "... kernel/perftests_data.o"
	@echo "... kernel/perftests_data.i"
	@echo "... kernel/perftests_data.s"
	@echo "... kernel/process.o"
	@echo "... kernel/process.i"
	@echo "... kernel/process.s"
	@echo "... kernel/string_util.o"
	@echo "... kernel/string_util.i"
	@echo "... kernel/string_util.s"
	@echo "... kernel/syscalls.o"
	@echo "... kernel/syscalls.i"
	@echo "... kernel/syscalls.s"
	@echo "... kernel/term.o"
	@echo "... kernel/term.i"
	@echo "... kernel/term.s"
	@echo "... kernel/timer.o"
	@echo "... kernel/timer.i"
	@echo "... kernel/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

