#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause

PROJ_DIR="@CMAKE_SOURCE_DIR@"
TCROOT="@TCROOT@"
ARCH="@ARCH@"
HOST_ARCH="@HOST_ARCH@"
VER="@GCC_TC_VER_@"

if [ @USE_SYSCC@ = 0 ]; then
   GCC_TC="$TCROOT/host_$HOST_ARCH/gcc_${VER}_${ARCH}_glibc/bin"
   export PATH="$GCC_TC:$PATH"
else
   export SYS_CC="@SYS_CC@"
   export SYS_CXX="@SYS_CXX@"
   export PATH="$PROJ_DIR/scripts/build_scripts:$PATH"
fi

"$TCROOT/$ARCH/musl/install/bin/musl-g++" "$@" -Wl,-m -Wl,@ARCH_LD_OUTPUT@

