/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

/* ------ Value-based config variables -------- */
#define KRN_TIMER_HZ                   @KRN_TIMER_HZ@
#define KRN_SCHED_LATENCY_TICKS        @KRN_SCHED_LATENCY_TICKS@
#define KRN_MIN_GRANULARITY_TICKS      @KRN_MIN_GRANULARITY_TICKS@

/* --------- Boolean config variables --------- */
#cmakedefine01 KRN_RESCHED_ENABLE_PREEMPT
#cmakedefine01 KRN_MINIMAL_TIME_SLICE

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are some pseudo-constants not designed to be easily changed
 * because of the code makes assumptions about them. Because of that, those
 * constants are hard-coded and not available as CMake variables. With time,
 * some of those constants get "promoted" and moved in CMake, others remain
 * here. See the comments and think about the potential implications before
 * promoting a hard-coded constant to a configurable CMake variable.
 */
#define MEASURE_BOGOMIPS_TICKS        (KRN_TIMER_HZ / 10)
#define BOGOMIPS_CONST                          10000


/*
 * Dynamic time slice (CFS step 7). The per-tick slice budget is
 *
 *    slice = max(SCHED_LATENCY_TICKS / nr_running, MIN_GRANULARITY_TICKS)
 *
 * with `nr_running` = runnable_tasks_count + 1 (folding curr back
 * in). Under light load the slice approaches the full latency
 * target (good for cache locality); under contention it shrinks
 * toward the floor (good for fairness / interactive latency).
 *
 * KRN_MINIMAL_TIME_SLICE is the stress-test override: pin both
 * SCHED_LATENCY and MIN_GRANULARITY to 1 so every tick is a
 * preemption point.
 */
#if !KRN_MINIMAL_TIME_SLICE

   #define SCHED_LATENCY_TICKS         KRN_SCHED_LATENCY_TICKS
   #define MIN_GRANULARITY_TICKS       KRN_MIN_GRANULARITY_TICKS

#else

   #define SCHED_LATENCY_TICKS         1
   #define MIN_GRANULARITY_TICKS       1

#endif
