/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once
#include <tilck_gen_headers/config_global.h>

#define KMALLOC_FIRST_HEAP_SIZE (@KRN_KMALLOC_FIRST_HEAP_SIZE_KB_VAL@ * KB)

/* --------- Boolean config variables --------- */

#cmakedefine01 KRN_KMALLOC_FREE_MEM_POISONING
#cmakedefine01 KRN_KMALLOC_HEAVY_STATS
#cmakedefine01 KRN_KMALLOC_SUPPORT_DEBUG_LOG
#cmakedefine01 KRN_KMALLOC_SUPPORT_LEAK_DETECTOR


/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are many dervied constants and convenience constants not
 * designed to be easily changed because of the code makes assumptions about
 * them. Because of that, those constants are hard-coded and not available as
 * CMake variables. With time, some of those constants get "promoted" and moved
 * in CMake, others remain here. See the comments and think about the potential
 * implications before promoting a hard-coded constant to a configurable CMake
 * variable.
 */

/* --- NOTHING HERE at the moment --- */
