/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE for kernel-private config variables.
 * The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/kernel/tilck_gen_headers/.
 */

#pragma once

#include <tilck_gen_headers/modules_config.h>

#cmakedefine01    KRN_TRACE_PRINTK_ON_BOOT

#ifdef KERNEL_TEST
   #define MOD_tracing_actual 1
#else
   #define MOD_tracing_actual MOD_tracing
#endif
