/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE for kernel-private config variables.
 * The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/kernel/tilck_gen_headers/.
 */

#pragma once

#include <tilck_gen_headers/modules_config.h>

#ifdef KERNEL_TEST
   #define MOD_sysfs_actual 1
#else
   #define MOD_sysfs_actual MOD_sysfs
#endif
