/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/kernel/tilck_gen_headers/.
 *
 * Kernel-private kb8042 module config. Shared variables (MOD_kb8042,
 * PS2_DO_SELFTEST, PS2_VERBOSE_DEBUG_LOG) are in modules_config.h.
 */

#pragma once
#include <tilck_gen_headers/modules_config.h>
