/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/kernel/tilck_gen_headers/.
 *
 * Kernel-private fb module config. MOD_fb is in modules_config.h.
 */

#pragma once
#include <tilck_gen_headers/modules_config.h>

/* ------ Value-based config variables -------- */

#define KRN_FBCON_BIGFONT_THR      @KRN_FBCON_BIGFONT_THR@

/* --------- Kernel-private boolean config variables --------- */

#cmakedefine01    KRN_FB_CONSOLE_BANNER
#cmakedefine01    KRN_FB_CONSOLE_CURSOR_BLINK
#cmakedefine01    KRN_FB_CONSOLE_USE_ALT_FONTS
#cmakedefine01    KRN_FB_CONSOLE_FAILSAFE_OPT

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 */

#define FBCON_OPT_FUNCS_MIN_FREE_HEAP                        (16 * MB)
#define FAILSAFE_FB_VADDR                 (BASE_VA + (1024 - 64) * MB)
