#!/usr/bin/python3
# SPDX-License-Identifier: BSD-2-Clause

import os
import re
import sys
import time
import signal
import subprocess
import threading
import struct
import fcntl
import filecmp
from collections import namedtuple

# Local imports
from utils import * # pylint: disable=unused-wildcard-import

# Constants coming from CMake (this file gets pre-processed by CMake)
TILCK_IMAGE = "@IMG_FILE@"
TMP_DIR = "@CMAKE_BINARY_DIR@/tmp"

# Other constants
STABLE_SCREENSHOT_DELAY   = 0.25
STABLE_SCREENSHOT_TIMEOUT = 3.00

QEMU_SPECIAL_KEYS = {
   " "  : "spc",
   "!"  : "shift-1",
   '"'  : "shift-apostrophe",
   "#"  : "shift-3",
   "$"  : "shift-4",
   "%"  : "shift-5",
   "&"  : "shift-7",
   "'"  : "apostrophe",
   "("  : "shift-9",
   ")"  : "shift-0",
   "*"  : "shift-8",
   "+"  : "shift-equal",
   ","  : "comma",
   "-"  : "minus",
   "."  : "dot",
   "/"  : "slash",
   ":"  : "shift-semicolon",
   ";"  : "semicolon",
   "<"  : "shift-comma",
   "="  : "equal",
   ">"  : "shift-dot",
   "?"  : "shift-slash",
   "@"  : "shift-2",
   "["  : "bracket_left",
   "\\" : "backslash",
   "]"  : "bracket_right",
   "^"  : "shift-6",
   "_"  : "shift-minus",
   "`"  : "grave_accent",
   "{"  : "shift-bracket_left",
   "|"  : "shift-backslash",
   "}"  : "shift-bracket_right",
   "~"  : "shift-grave_accent"
}

KEYS_MAP = {
   chr(x):
      chr(x)
         if x in range(ord('a'), ord('z')+1) or x in range(ord('0'),ord('9')+1)
         else
         'shift-' + chr(x).lower()
            if x in range(ord('A'), ord('Z')+1)
            else
            QEMU_SPECIAL_KEYS[chr(x)]
               if chr(x) in QEMU_SPECIAL_KEYS
               else None

   for x in range(27, 128)
}

# Environment config variables
VM_MEMORY_SIZE_IN_MB = int(os.environ.get('TILCK_VM_MEM', '128'))

# Global state variables
g_process = None
g_fail_reason = Fail.success
g_dumping_gcda_files = False
g_timeout = 20
g_next_screenshot = 0

def set_once_qemu_process(p):
   global g_process
   assert(g_process is None)
   g_process = p

def set_once_fail_reason(reason: Fail):
   global g_fail_reason
   assert(g_fail_reason == Fail.success)
   g_fail_reason = reason

def wait_for_qemu_to_exit():
   while g_process.poll() is None:
      time.sleep(0.1)

def recv_from_qemu_monitor():

   read_anything = False
   buf = ''

   while True:

      text = g_process.stdout.read()

      # Is there any new text?
      if text:
         buf += text.decode('latin-1')
         read_anything = True
         time.sleep(0.05)
         continue

      # Nope. Did we read anything in the previous iteration?
      if read_anything:
         return buf # yep, return.

      # Nope. Is the VM still alive?
      if g_process.poll() is not None:
         return '' # Nope. Return an empty string

      # Yep. Wait for some text
      time.sleep(0.1)

def echo_qemu_monitor():
   text = recv_from_qemu_monitor()
   raw_stdout_write(text)

def send_to_qemu_monitor(cmd, delay = 0.2):
   g_process.stdin.write("{}\n".format(cmd).encode('latin-1'))
   g_process.stdin.flush()
   time.sleep(delay)
   echo_qemu_monitor()

def send_single_key_to_vm(key):

   key_name = None

   if not key:
      return

   if len(key) > 1:
      key_name = key
   else:
      key_name = KEYS_MAP.get(key, None)

   if key_name is not None:
      send_to_qemu_monitor("sendkey " + key_name)

def send_string_to_vm(s):
   for k in s:
      send_single_key_to_vm(k)

def run(test_func):

   args = [
      'qemu-system-i386',
      '-m', str(VM_MEMORY_SIZE_IN_MB),
      '-display', 'none',
      '-monitor', 'stdio',
      '-device', 'isa-debug-exit,iobase=0xf4,iosize=0x04',
      '-drive', 'id=img1,format=raw,if=none,file=' + TILCK_IMAGE,
      '-device', 'ide-hd,drive=img1,cyls=74,heads=16,secs=63'
   ]

   if is_kvm_installed():
      args.append('-enable-kvm')

   # Run the QEMU process by using a PIPE for its stdout
   p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
   set_once_qemu_process(p)

   # Get the current flags for the `stdout` file descriptor
   fl = fcntl.fcntl(g_process.stdout.fileno(), fcntl.F_GETFL)

   # Make the `stdout` file descriptor non-blocking
   fcntl.fcntl(g_process.stdout.fileno(), fcntl.F_SETFL, fl | os.O_NONBLOCK)

   raw_print('-' * 80)
   start_time = time.time()
   echo_qemu_monitor()

   try:

      # Call the test func
      test_func()

   except Exception as e:

      msg_print("Exception: " + str(e))

   send_to_qemu_monitor("quit")
   wait_for_qemu_to_exit()

   elapsed = time.time() - start_time
   raw_print('-' * 80)
   msg_print("Elapsed: {:.2f} s".format(elapsed))

def delete_old_screenshots():

   for f in os.listdir():

      if not os.path.isfile(f):
         continue

      if re.match("s[0-9]+[.](ppm|png)", f):
         os.remove(f)

def vm_take_screenshot():

   global g_next_screenshot

   name = "s{:03}".format(g_next_screenshot)
   full_name = name + ".ppm"
   send_to_qemu_monitor("screendump " + full_name)
   g_next_screenshot += 1
   return full_name

def vm_take_stable_screenshot():

   time_elapsed = 0.0
   prevs = [vm_take_screenshot()]
   curr = None

   while True:

      time_elapsed += STABLE_SCREENSHOT_DELAY

      if time_elapsed >= STABLE_SCREENSHOT_TIMEOUT:
         tstr = str(STABLE_SCREENSHOT_TIMEOUT)
         raise RuntimeError("Unable to take a stable screenshot in "+tstr+"s")

      time.sleep(STABLE_SCREENSHOT_DELAY)
      curr = vm_take_screenshot()

      if filecmp.cmp(prevs[-1], curr, False):
         break # Bang! We got two identical screenshots.

      # We screenshots differ.
      if len(prevs) > 1:

         # We have more than 1 old screeshot. Could be the cursor blinking?
         if filecmp.cmp(prevs[-2], curr, False):
            break # Assume it's cursor blinking.

      # We have to save this screenshot
      prevs.append(curr)

   # Great, we're out of the loop. Let's delete the useless screenshots.
   for s in prevs:
      os.remove(s)

   return curr


def trivial_func():
   vm_take_stable_screenshot()
   time.sleep(1)
   vm_take_stable_screenshot()
   time.sleep(1)
   send_string_to_vm("1")
   time.sleep(1)
   vm_take_stable_screenshot()
   send_string_to_vm("ls -l")
   send_single_key_to_vm("ret")
   vm_take_stable_screenshot()

def main():

   set_runner_name("interactive tests runner")
   detect_kvm()

   if not os.path.isdir(TMP_DIR):
      os.mkdir(TMP_DIR)

   os.chdir(TMP_DIR)
   delete_old_screenshots()

   thread = threading.Thread(target = run, args = (trivial_func,))
   thread.start()
   thread.join(g_timeout)

   if thread.is_alive():

      # If we get here, after `g_params.timeout`, the test is still running

      if g_dumping_gcda_files:

         # If we're just dumping the GCDA file, wait a little more
         thread.join(30)

      if thread.is_alive():
         # We have to fail with timeout
         set_once_fail_reason(Fail.timeout)
         print_timeout_kill_vm_msg(g_timeout)
         g_process.send_signal(signal.SIGINT)
         thread.join()


###############################
if __name__ == '__main__':
   main()
