#!/usr/bin/python3
# SPDX-License-Identifier: BSD-2-Clause

import os
import re
import sys
import time
import signal
import subprocess
import threading

# Local imports
from utils import * # pylint: disable=unused-wildcard-import

# Constants

SHORT_TEST_TIMEOUT = 12
MED_TEST_TIMEOUT   = 24
LONG_TEST_TIMEOUT  = 60

test_types = ['selftest', 'shellcmd']
pretty_names_list = ['Self tests', 'Shell cmd tests']
load_tests_func_by_type_list = [
   'load_list_of_kernel_self_tests',
   'load_list_of_shell_cmd_tests'
]

tt_pretty_names = {
   val: pretty_names_list[i] for i, val in enumerate(test_types)
}

load_tests_func_by_type = {
   val: load_tests_func_by_type_list[i] for i, val in enumerate(test_types)
}

tt_indexes = {
   val : i for i, val in enumerate(test_types)
}

# Global variables

tests_by_type = { k: [] for k in test_types }
tests_to_run = { k: 0 for k in test_types }
tests_passed = { k: 0 for k in test_types }

def load_all_tests():

   global tests_by_type

   for tt in test_types:
      tests_by_type[tt] = globals()[load_tests_func_by_type[tt]]()

def load_list_of_shell_cmd_tests():

   result = []

   tt_short = SHORT_TEST_TIMEOUT
   tt_med = MED_TEST_TIMEOUT
   tt_long = LONG_TEST_TIMEOUT

   devshell = os.path.join(BUILD_DIR, 'userapps', 'devshell')
   output = subprocess.check_output([devshell, '-l']).decode("utf-8")
   arr = output.split("\n")

   for r in arr:

      r = r.rstrip()

      if not r:
         continue

      name, tt = r.split(' ')
      tt = locals()[tt]
      result.append([name, tt])

   return result

def load_list_of_kernel_self_tests():

   result = []
   rows = subprocess                            \
            .check_output(['nm', KERNEL_FILE])   \
               .decode("utf-8")                 \
                  .split("\n")

   t_short = SHORT_TEST_TIMEOUT
   t_med = MED_TEST_TIMEOUT
   t_long = LONG_TEST_TIMEOUT

   for row in rows:

      row = row.rstrip()

      if not row:
         continue

      vaddr, t, name = row.split(' ')

      if not name.startswith('selftest_'):
         continue

      comps = name.split('_')
      tt = comps[-1]

      if tt not in ['short', 'med', 'long']:
         continue

      name = '_'.join(comps[1:])
      tt = locals()["t_" + tt]
      result.append([name, tt])

   return result

def internal_run_test(test_type, test, timeout, show_output = False):

   print("[ RUNNING ] {}: '{}' [timeout: {}]".format(test_type, test, timeout))
   start_time = time.time()

   try:
      output = subprocess.check_output(
         [
            '@CMAKE_BINARY_DIR@/st/single_test_run',
            test_type,
            test,
            str(timeout)
         ],
         stderr=subprocess.STDOUT
      ).decode('utf-8')

   except subprocess.CalledProcessError as e:
      elapsed = time.time() - start_time
      raw_print(e.output.decode('utf-8'))
      print("[ FAILED  ] after {:.2f} seconds with: {}\n"
               .format(elapsed, error_codes_strings[e.returncode]))
      return False

   elapsed = time.time() - start_time

   if show_output:
      print("")
      raw_print(output)

   print("[ PASSED  ] after {:.2f} seconds\n".format(elapsed))
   return True

def show_help_and_exit():
   print("Syntax:")
   print("     run_all_tests -l")
   print("     run_all_tests [-c] [-o] [<regex>] [<max_timeout>]")
   sys.exit(1)

def show_tests_and_exit():

   col_names = [['test name', 30], ['test type', 12],  ['timeout', 10]]
   print("")

   for x in col_names:
      sys.stdout.write('+-')
      sys.stdout.write(''.center(x[1], '-'))
   sys.stdout.write('+\n')

   for x in col_names:
      sys.stdout.write('| ')
      sys.stdout.write(x[0].center(x[1], ' '))
   sys.stdout.write('|\n')

   for x in col_names:
      sys.stdout.write('+-')
      sys.stdout.write(''.center(x[1], '-'))
   sys.stdout.write('+\n')

   for tt in test_types:

      for x in tests_by_type[tt]:
         sys.stdout.write('| ')
         sys.stdout.write(x[0].ljust(col_names[0][1]))
         sys.stdout.write('| ')
         sys.stdout.write(tt.ljust(col_names[1][1]))
         sys.stdout.write('| ')
         sys.stdout.write(str(x[1]).ljust(col_names[2][1]))
         sys.stdout.write('|\n')

      for x in col_names:
         sys.stdout.write('+-')
         sys.stdout.write(''.center(x[1], '-'))
      sys.stdout.write('+\n')

   sys.stdout.write('\n')
   sys.exit(0)

def get_sum(per_test_counter):
   return sum(per_test_counter[k] for k in per_test_counter)

def run_test(test_type, x, show_output):

   global tests_to_run, tests_passed

   if get_sum(tests_to_run) == 0:
      print("")

   tests_to_run[test_type] += 1
   if internal_run_test(test_type, x[0], x[1], show_output):
      tests_passed[test_type] += 1

def run_all_tests(max_test_timeout, show_output, reg, fail_on_zero):

   for tt in test_types:
      for x in tests_by_type[tt]:
         if re.match(reg, x[0]) and x[1] <= max_test_timeout:
            run_test(tt, x, show_output)

   if fail_on_zero:
      if tests_to_run['selftest'] + tests_to_run['shellcmd'] == 0:

         found = []
         for tt in test_types:
            for x in tests_by_type[tt]:
               if re.match(reg, x[0]):
                  found.append(x)

         if not found:
            print("ERROR: No tests matching the '{}' regex.".format(reg))
         else:
            print("ERROR: No tests matching "
                  "the '{}' regex having timeout <= {}"
                     .format(reg, max_test_timeout))
            print("Tests matching the regex with timeout > {}:"
                     .format(max_test_timeout))
            for x in found:
               print("  {} [timeout: {}s]".format(x[0].ljust(20), x[1]))

         sys.exit(1)

def dump_test_stats():

   print('-' * 80)

   for tt in test_types:
      if tests_to_run[tt]:
         print("{} passed: {}/{}"
                  .format(tt_pretty_names[tt],
                          tests_passed[tt],
                          tests_to_run[tt]))

def main():

   global tests_by_type
   global tests_to_run

   # Options
   max_test_timeout = MED_TEST_TIMEOUT
   show_output = False
   compact_shellcmds = False
   reg_filter = ".*"
   # ------------

   load_all_tests()

   if len(sys.argv) >= 2 and sys.argv[1] == '-c':
      compact_shellcmds = True
      tests_by_type['shellcmd'] = []
      del sys.argv[1]

   if len(sys.argv) >= 2 and sys.argv[1] == '-o':
      show_output = True
      del sys.argv[1]

   if len(sys.argv) >= 2:

      if sys.argv[1] == '-l':
         show_tests_and_exit()

      if sys.argv[1].startswith('-'):
         show_help_and_exit()

      try:
         max_test_timeout = int(sys.argv[1])
      except:
         reg_filter = sys.argv[1]

      if len(sys.argv) >= 3:
         try:
            max_test_timeout = int(sys.argv[2])
         except:
            show_help_and_exit()

   run_all_tests(max_test_timeout,
                 show_output,
                 reg_filter,
                 not compact_shellcmds)

   if compact_shellcmds:
      run_test('shellcmd', ['runall', MED_TEST_TIMEOUT * 2], show_output)

   dump_test_stats()

   if get_sum(tests_passed) != get_sum(tests_to_run):
      sys.exit(1)

###############################
if __name__ == '__main__':
   main()
