trigger:

  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    exclude:
      - README.md
      - docs/**
      - scripts/configurator/**

jobs:
  - job: gcc_12_3
    container: 'vvaltchev/tilck-riscv64:v2'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      CI: 1
      ARCH: riscv64
      TCROOT: /tc/toolchain2-gcc123
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 12.3.0
      CMAKE_ARGS: >
        -DKMALLOC_FREE_MEM_POISONING=1
        -DKERNEL_UBSAN=1
        -DKERNEL_SAT=1
        -DKRN_MINIMAL_TIME_SLICE=1
        -DKRN_RESCHED_ENABLE_PREEMPT=1
        -DTIMER_HZ=500
        -DKRN_CLOCK_DRIFT_COMP=0
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: gcc_13_3
    container: 'vvaltchev/tilck-riscv64:v2'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      CI: 1
      ARCH: riscv64
      TCROOT: /tc/toolchain2-gcc133
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 13.3.0
      CMAKE_ARGS: >
        -DKMALLOC_FREE_MEM_POISONING=1
        -DKERNEL_UBSAN=1
        -DKERNEL_SAT=1
        -DKRN_MINIMAL_TIME_SLICE=1
        -DKRN_RESCHED_ENABLE_PREEMPT=1
        -DTIMER_HZ=500
        -DKRN_CLOCK_DRIFT_COMP=0
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/cmake_run
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: coverage
    container: 'vvaltchev/tilck-riscv64:v2'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      CI: 1
      ARCH: riscv64
      TCROOT: /tc/toolchain2-gcc123
      GTEST_SHUFFLE: 0
      DUMP_COV: 1
      REPORT_COV: 1
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 12.3.0
      CMAKE_ARGS: >
        -DKMALLOC_FREE_MEM_POISONING=1
        -DKERNEL_UBSAN=1
        -DKERNEL_SAT=1
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/gcc_gcov
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
      - script: ./build/scripts/generate_kernel_coverage_report --codecov
        displayName: Gen kernel gcov report and upload to codecov

