#!/usr/bin/env bash

pkg="$1"
ci=

if [ "$1" == "-ci" ]; then
   pkg="$2"
   ci=1
fi

if ! rpm -q $pkg &> /dev/null; then

   echo "We need to install the package $1"

   if [ "$ci" == 1 ]; then
      cmd="zypper install -y $pkg"
   else
      cmd="sudo zypper install $pkg"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

