#!/usr/bin/env bash

if ! rpm -q $1 &> /dev/null; then

   echo "We need to install the package $1"

   if [ "$RUNNING_IN_CI" == 1 ]; then
      cmd="zypper install -y $1"
   else
      cmd="sudo zypper install $1"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

