#!/usr/bin/python

import os
import re
import sys
import time
import signal
import subprocess
import threading

TEST_TIMEOUT = 8
VM_MEMORY_SIZE_IN_MB = 256
KERNEL_HELLO_MSG = 'Hello from exOS!'
KERNEL_FILE = './build/elf_kernel_stripped'
FATPART_FILE = './build/fatpart'

# Fail codes:
FAIL_SUCCESS = 0
FAIL_REBOOT = 2
FAIL_TIMEOUT = 3
FAIL_PANIC = 4
FAIL_SHELL_NO_ZERO_EXIT = 5

output = ""
process = None
failed = FAIL_SUCCESS
hello_msg_found = False
shell_exit_code = -1

def RunTheVM():

   global output
   global process
   global failed
   global hello_msg_found
   global shell_exit_code



   args = ['qemu-system-i386',
           '-m', str(VM_MEMORY_SIZE_IN_MB),
           '-kernel', KERNEL_FILE,
           '-nographic', '-device',
           'isa-debug-exit,iobase=0xf4,iosize=0x04']

   if not os.environ.get('TRAVIS', False):
      args.append('-enable-kvm')

   if sys.argv[1] == 'shellcmd':

      print "Running the VM with shell command '{0}'...".format(sys.argv[2])

      args += ['-initrd', FATPART_FILE,
               '-append', '-cmd /sbin/init -- -c {0}'.format(sys.argv[2])]

   elif sys.argv[1] == 'selftest':

      print "Running the VM with selftest '{0}'...".format(sys.argv[2])
      args += ['-append', '-s={0}'.format(sys.argv[2])]

   else:
      sys.exit(1)

   print "-"*80, "\n"
   process = subprocess.Popen(args, stdout=subprocess.PIPE)

   for line in iter(process.stdout.readline,''):
      output += line
      stripped = line.rstrip()

      print stripped

      m = re.search(r'\[init\] the shell exited with status: ([0-9]+)',
                    stripped)

      if m:
         shell_exit_code = int(m.group(1))
         continue

      if stripped.find(KERNEL_HELLO_MSG) != -1:
         if not hello_msg_found:
            hello_msg_found = True
         else:
            print "\n[system test runner] Detected TWICE the kernel " + \
                  "hello msg: likely the machine rebooted."
            print "[system test runner] KILLING the VM."

            failed = FAIL_REBOOT
            process.send_signal(signal.SIGINT)
         continue

   print "-"*80

###############################################################################
# MAIN

def show_help_and_exit():
   print "Syntax: "
   print "  run_system_test selftest <selftest name>"
   print "  run_system_test shellcmd <shell cmd name>"
   sys.exit(1)

if len(sys.argv) < 3:
   show_help_and_exit()

if sys.argv[1] not in ['selftest', 'shellcmd']:
   show_help_and_exit()

thread = threading.Thread(target = RunTheVM)
thread.start()
thread.join(TEST_TIMEOUT)

if thread.is_alive():
   failed = FAIL_TIMEOUT

   print "[system test runner] The VM is alive after the timeout " + \
         "of {0} seconds. KILLING IT.".format(TEST_TIMEOUT)

   process.send_signal(signal.SIGINT)
   thread.join()

if output.find("KERNEL PANIC") != -1:
   failed = FAIL_PANIC

if sys.argv[1] == 'shellcmd' and failed == 0 and shell_exit_code != 0:
   print "Shell exited with code {0}.".format(shell_exit_code)
   failed = FAIL_SHELL_NO_ZERO_EXIT


sys.exit(failed)

