#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

# GLOBAL VARIABLES

# Project's root directory
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_DIR="$(cd $SOURCE_DIR/../.. && pwd)"

# Include files
source $MAIN_DIR/scripts/bash_includes/script_utils

# CONSTANTS

CM=$MAIN_DIR/scripts/cmake_run

##############################################################

$CM -DKERNEL_TRACK_NESTED_INTERRUPTS=0
