#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

# GLOBAL VARIABLES

# Project's root directory
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_DIR="$(cd $SOURCE_DIR/../.. && pwd)"

# Include files
source $MAIN_DIR/scripts/bash_includes/script_utils

# CONSTANTS

CM=$MAIN_DIR/scripts/cmake_run

##############################################################

$CM                                   \
      -DCMAKE_BUILD_TYPE=MinSizeRel   \
      -DBOOTLOADER_EFI=0              \
      -DKERNEL_SHOW_LOGO=0            \
      -DKERNEL_SYMBOLS=0              \
      -DKERNEL_SELFTESTS=0            \
      -DMOD_console=0                 \
      -DMOD_fb=0                      \
      -DMOD_kb8042=0                  \
      -DMOD_tracing=0                 \
      -DMOD_acpi=0                    \
      -DMOD_serial=1                  \
      -DTINY_KERNEL=1                 \
      -DUSERAPPS_extra=0              \
      -DTYPICAL_DEVEL_USERAPPS=0      \
      "$@"
