#!/usr/bin/env bash

if ! pacman -Q $1 &> /dev/null; then

   echo "We need to install the package $1"

   if [ "$RUNNING_IN_CI" == 1 ]; then
      cmd="pacman -S --noconfirm $1"
   else
      cmd="sudo pacman -S $1"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

