#!/usr/bin/env bash

pkg="$1"
ci=

if [ "$1" == "-ci" ]; then
   pkg="$2"
   ci=1
fi

if ! pacman -Q $pkg &> /dev/null; then

   echo "We need to install the package $pkg"

   if [ "$ci" == 1 ]; then
      cmd="pacman -S --noconfirm $pkg"
   else
      cmd="sudo pacman -S $pkg"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

