#!/usr/bin/python

import os
import sys
import subprocess

firstPrint = False

while True:

   line = sys.stdin.readline().rstrip()

   if line.find("KERNEL STACKTRACE") != -1:
      continue
   if line.find("END STACKTRACE") != -1:
      break

   frame, vaddr = line.split(": ")
   out = subprocess.check_output(['addr2line',
                                  '-s', '-f', '-e',
                                  'build/kernel/elf_kernel', vaddr])

   if not firstPrint:
      print "\n\n"
      firstPrint = True

   func, f = out.splitlines()
   print "{0}() in {1}\n".format(func, f)
