#!/usr/bin/python

import os
import sys
import subprocess

firstPrint = False

while True:

   line = sys.stdin.readline().rstrip()

   if not firstPrint:
      print "\n\n"
      firstPrint = True

   addrs_list = line.split(" ")

   for i, vaddr in enumerate(addrs_list):
      out = subprocess.check_output(['addr2line',
                                     '-s', '-f', '-e',
                                     'build/kernel/elf_kernel', vaddr])

      func, f = out.splitlines()
      print "[Frame {}] [{}] {}() in {}\n".format(i, vaddr, func, f)
