#!/usr/bin/env bash

pkg="$1"
ci=

if [ "$1" == "-ci" ]; then
   pkg="$2"
   ci=1
fi

if ! [ "`dpkg -s $pkg 2>&1 | grep Status`" ]; then

   echo "We need to install the package $pkg"

   if [ "$ci" == 1 ]; then
      cmd="apt install -y $pkg"
   else
      if ! which sudo &> /dev/null; then
         cmd="su -c \"apt install $pkg\""
      else
         cmd="sudo apt install $pkg"
      fi
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

