#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

function save_cc_vars {

   if [[ "$HOST_ARCH" == "$ARCH" ]]; then
      export AR=${AR:-ar}
      export NM=${NM:-nm}
      export RANLIB=${RANLIB:-ranlib}
   fi

   saved_CC=$CC
   saved_CXX=$CXX
   saved_AR=$AR
   saved_NM=$NM
   saved_RANLIB=$RANLIB
}

function set_cc_vars_to_tc {

   export CC="${ARCH_GCC_TC}-linux-gcc"
   export CXX="${ARCH_GCC_TC}-linux-g++"
   export AR="${ARCH_GCC_TC}-linux-ar"
   export NM="${ARCH_GCC_TC}-linux-nm"
   export RANLIB="${ARCH_GCC_TC}-linux-ranlib"
   export CROSS_PREFIX="${ARCH_GCC_TC}-linux-"
   export CROSS_COMPILE=$CROSS_PREFIX
}

function reset_cc_vars_to_null {

   export CC=""
   export CXX=""
   export AR=""
   export NM=""
   export RANLIB=""
   export CROSS_PREFIX=""
   export CROSS_COMPILE=""
}

function reset_cc_vars {

   export CC=$saved_CC
   export CXX=$saved_CXX
   export AR=$saved_AR
   export NM=$saved_NM
   export RANLIB=$saved_RANLIB
   export CROSS_PREFIX=""
   export CROSS_COMPILE=""
}

