#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

############################################
# CONSTANTS

VERSION_REGEX='[0-9]+[.][0-9]+[.][0-9]+'

RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
LGRAY='\033[0;37m'
DGRAY='\033[1;37m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LBLUE='\033[1;34m'
LMAGENTA='\033[1;35m'
LCYAN='\033[1;36m'
WHITE='\033[1;37m'
RATTRS='\033[0m'

export RUNNING_IN_CI=0

if [ -n "$TRAVIS" ]; then

   echo "Detected TRAVIS CI"
   export RUNNING_IN_CI=1

elif [ -n "$CIRCLECI" ]; then

   echo "Detected CIRCLE CI"
   export RUNNING_IN_CI=1

elif [ -n "$AZURE_HTTP_USER_AGENT" ]; then

   echo "Detected AZURE PIPELINES CI"
   export RUNNING_IN_CI=1

else

   echo "No CI detected: assuming user machine"
fi

############################################
# FUNCTIONS

# $1 version in the format "major.minor.patchlevel"
# $2 component number to get (1 => major, 2 => minor, 3 => patchlevel)
function get_version_comp {
   echo -ne $1 | grep -Eo '[0-9]+' | head -$2 | tail -1
}

# $1 = program name
function generic_get_version_str {
   $1 --version | head -1 | grep -Eo "$VERSION_REGEX" | head -1
}

# $1 = command
function run_command {
   echo "Running command: $1"
   eval "$1"
}

# $1 = command
# $2 = output file
function run_command2 {
   echo "Running command: $1 &> $2"
   eval "$1 &> $2"
}

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

function show_work_on_component_msg {
   echo
   echo "*** $1 ***"
   echo
}

function show_skip_component_msg {
   echo "NOTE: Skipping $1"
}

# $1 = program name
# $2 = min version string
function show_too_old_and_exit {
   echo "System's $1 is too old. Version >= $2 is required."
   exit 1
}

# $1 = program name
# $2 = current version string (i.e. "1.2.3")
# $3 = min version string (i.e. "1.2.3")
function fail_if_too_old {

   major=$(get_version_comp $2 1)
   minor=$(get_version_comp $2 2)
   echo "[cmake_run] $1 version (parsed): $major.$minor"

   min_major=$(get_version_comp $3 1)
   min_minor=$(get_version_comp $3 2)

   if [ $major -lt $min_major ]; then
      show_too_old_and_exit $1 $3
   elif [ $major -eq $min_major ] && [ $minor -lt $min_minor ]; then
      show_too_old_and_exit $1 $3
   fi
}

function download_file_in_cache {

   local url="$1"
   local filename="$2"

   if ! [ -f cache/$filename ]; then
      (cd cache && wget $url/$filename)
   else
      echo "NOTE: Skipping the download of $filename"
   fi
}

function extract_cachefile_tar_gz {

   local tarfile="$1"
   local internalDirName="$2"
   local newDirName="$3"

   echo "Extracting $tarname..."
   tar xfz cache/$tarname
   mv "$internalDirName" "$newDirName"
}

function extract_cachefile_tar_bz {

   local tarfile="$1"
   local internalDirName="$2"
   local newDirName="$3"

   echo "Extracting $tarname..."
   tar xfj cache/$tarname
   mv "$internalDirName" "$newDirName"
   echo "Extracting completed."
}

function install_32bit_libs {

   if ! [ -f $TC/.distro ]; then

      echo "Unable to check the presence of 32-bit glibc on this system: "
      echo "Linux distribution not fully supported by this script"
      echo "WARNING: the current operation might fail"
      return
   fi

   if ! [ -f $TC/.32bit_libs_pkg ]; then
      echo "Internal error: $TC/.32bit_libs_pkg does not exist"
      return
   fi

   distro=`cat $TC/.distro`
   pkg=`cat $TC/.32bit_libs_pkg`
   install_pkg="$MAIN_DIR/scripts/tc/$distro/install_pkg"

   if [ "$RUNNING_IN_CI" == 1 ]; then
      $install_pkg -ci $pkg
   else
      $install_pkg $pkg
   fi
}
