#!/bin/bash

maindir="@CMAKE_SOURCE_DIR@"
bdir="@CMAKE_BINARY_DIR@"
dest="@CMAKE_BINARY_DIR@/fatpart"
tc="@TCROOT@"

mtoolsdir=$tc/mtools
mformat=$mtoolsdir/mformat
mlabel=$mtoolsdir/mlabel
mmd=$mtoolsdir/mmd
mcopy=$mtoolsdir/mcopy

if [ ! -f $dest ]; then
   # If the 'fatpart' file does not already exist
   dd status=none if=/dev/zero of=$dest bs=1M count=35
fi

# mformat options
# -d <N> ; num of FAT copies
# -F     ; force FAT32 to be used
# -c <N> ; sectors per cluster
# -t <N> ; cylinders
# -h <N> ; heads
# -s <N> ; sectors
$mformat -i $dest -d 1 -F -c 1 -t 70 -h 16 -s 63 ::
$mlabel -i $dest ::EXOS

rm -rf $bdir/sysroot
cp -r $maindir/sysroot $bdir/

# Remove the README file that is not supposed to be in the actual sysroot
rm $bdir/sysroot/README

cd $bdir/sysroot
ln $bdir/usermode_apps/init sbin/

for x in $bdir/usermode_apps/*; do
   if [ -x "$x" ] && [ ! -d "$x" ] && [ "`basename $x`" != "init" ]; then
      ln $x bin/
   fi
done


# hard-link EFI files
ln @EFI_x86_64_FILE@ EFI/BOOT/
ln @EFI_ia32_FILE@ EFI/BOOT/

# hard-link the kernel file (used also by the legacy bootloader)
ln @KERNEL_FILE@ @KERNEL_FATPART_PATH@

if [ -d $tc/busybox ]; then
   ln $tc/busybox/busybox bin/
fi

# first, create the directories
for f in $(find * -type d); do
   $mmd -i $dest $f
done

# then, copy all the files in sysroot
for f in $(find * -type f); do
   $mcopy -i $dest $f ::/$f
done

