#!/bin/bash

pushd .

cd build

sudo losetup -D
sudo losetup /dev/loop0 ./tilck.img
sudo chmod o+rw /dev/loop0
rm -f tilck.vmdk
VBoxManage internalcommands createrawvmdk -filename tilck.vmdk -rawdisk /dev/loop0
sudo chown $USER tilck.vmdk
popd
