#!/usr/bin/env bash

BUILD_DIR="@CMAKE_BINARY_DIR@"
f="@GPT_IMG_FILE@"
tc="@TCROOT@"

if [ -z "$QEMU_BIOS" ]; then
   QEMU_BIOS="$tc/i386/ovmf/OVMF-pure-efi.fd"
fi

if ! [ -f "$QEMU_BIOS" ]; then
   echo "In order to boot with EFI, you need to download OVMF first."
   echo "To do that, just run in project's main directory:"
   echo "   ./scripts/build_toolchain -s download_ovmf"
   exit 1
fi

if ! [ -f $f ]; then
   echo "In order to boot with EFI, you need to build the gpt_image target:"
   echo "   make gpt_image"
   exit 1
fi

if [ -z "$GDB_PORT" ]; then
   GDB_PORT=1234
fi

echo "Run QEMU with -bios $QEMU_BIOS -gdb tcp::$GDB_PORT"

qemu-system-i386                                       \
   @QEMU_COMMON_OPTS@                                  \
   @QEMU_RAM_OPT@                                      \
   -gdb tcp::$GDB_PORT                                 \
   -bios "$QEMU_BIOS"                                  \
   -drive index=0,media=disk,format=raw,file=$f "$@"
