#!/usr/bin/env bash

BUILD_DIR=@CMAKE_BINARY_DIR@

if [ -z "$GDB_PORT" ]; then
   GDB_PORT=1234
fi

qemu-system-@ARCH@                                     \
   @QEMU_COMMON_OPTS@                                  \
   -gdb tcp::$GDB_PORT                                 \
   @QEMU_RAM_OPT@                                      \
   -drive id=img1,format=raw,if=none,file=@IMG_FILE@   \
   -netdev user,id=net0,hostfwd=udp::2222-:22          \
   -device e1000,netdev=net0                           \
   @QEMU_ARCH_OPTS@ $EXTRA_OPTS "$@"
