#!/usr/bin/env bash

if [ -z "$GDB_PORT" ]; then
   GDB_PORT=1234
fi

   BUILD_DIR=@CMAKE_BINARY_DIR@
   qemu-system-@ARCH@ @QEMU_COMMON_OPTS@ -gdb tcp::$GDB_PORT @QEMU_RAM_OPT@   \
      -drive id=img1,format=raw,if=none,file=@IMG_FILE@ @QEMU_ARCH_OPTS@ "$@"
