#!/bin/sh

BUILD_DIR="@CMAKE_BINARY_DIR@"
FATPART="$BUILD_DIR/fatpart"

if [ -z "$GDB_PORT" ]; then
   GDB_PORT=1234
fi

qemu-system-@ARCH@ @QEMU_COMMON_OPTS@ -gdb tcp::$GDB_PORT \
   @QEMU_RAM_OPT@ -kernel "@KERNEL_FILE@" -initrd "$FATPART" "$@"
