#!/usr/bin/env bash

BUILD_DIR="@CMAKE_BINARY_DIR@"
f="@GPT_IMG_FILE@"
tc="@TCROOT@"

if ! [ -d $tc/x86_64/ovmf ]; then
   echo "In order to boot with EFI, you need to download OVMF first."
   echo "To do that, just run in project's main directory:"
   echo "   ./scripts/build_toolchain -s download_ovmf"
   exit 1
fi

if ! [ -f $f ]; then
   echo "In order to boot with EFI, you need to build the gpt_image target:"
   echo "   make gpt_image"
   exit 1
fi

if [ -z "$GDB_PORT" ]; then
   GDB_PORT=1234
fi

qemu-system-x86_64 @QEMU_COMMON_OPTS@ -gdb tcp::$GDB_PORT @QEMU_RAM_OPT@    \
   -bios $tc/x86_64/ovmf/OVMF-pure-efi.fd                                   \
   -drive index=0,media=disk,format=raw,file=$f "$@"
