/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

/* --------- Boolean config variables --------- */
#cmakedefine01 PS2_DO_SELFTEST
#cmakedefine01 PS2_VERBOSE_DEBUG_LOG
