/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once
#include <tilck_gen_headers/config_global.h>
#include <tilck/common/page_size.h>

#define KERNEL_FILE_PATH       "/@KERNEL_FATPART_PATH@"
#define KERNEL_FILE_PATH_EFI   "\\@KERNEL_FATPART_PATH_EFI@"

#define SECTOR_SIZE            @SECTOR_SIZE@
#define BL_ST2_DATA_SEG        @BL_ST2_DATA_SEG@
#define BL_BASE_ADDR           @BL_BASE_ADDR@
#define BL_BASE_SEG            (@BL_BASE_ADDR@ / 16)
#define DISK_UUID              @DISK_UUID@
#define IMG_SZ_SEC             @IMG_SZ_SEC@       /* size of the whole image */
#define BOOT_SECTORS           @BOOT_SECTORS@     /* bootloader sectors      */
#define BOOTPART_SEC           @BOOTPART_SEC@     /* start of the bootpart   */
#define BOOTPART_SZ_SEC        @BOOTPART_SZ_SEC@  /* size of the bootpart    */
#define INITRD_SECTOR          @INITRD_SECTOR@    /* start of the initrd     */
#define INITRD_SZ_SEC          @INITRD_SZ_SEC@    /* size of the initrd      */
#define PREFERRED_GFX_MODE_W   @PREFERRED_GFX_MODE_W@
#define PREFERRED_GFX_MODE_H   @PREFERRED_GFX_MODE_H@

/* Boolean config variables */
#cmakedefine01 BOOTLOADER_POISON_MEMORY
#cmakedefine01 BOOT_ASK_VIDEO_MODE

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are many dervied constants and convenience constants like
 * COMPILER_NAME along with some pseudo-constants like KERNEL_MAX_END_PADDR not
 * designed to be easily changed because of the code makes assumptions about
 * them. Because of that, those constants are hard-coded and not available as
 * CMake variables. With time, some of those constants get "promoted" and moved
 * in CMake, others remain here. See the comments and think about the potential
 * implications before promoting a hard-coded constant to a configurable CMake
 * variable.
 */


#if !KERNEL_GCOV

   #if TINY_KERNEL
      #define KERNEL_MAX_SIZE            ( 512 * KB)
   #else
      #define KERNEL_MAX_SIZE            (1024 * KB)
   #endif

#else
   #define KERNEL_MAX_SIZE            (2048 * KB)
#endif

#define KERNEL_MAX_END_PADDR     (KERNEL_PADDR + KERNEL_MAX_SIZE)
