/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#define START_SCRIPT    "@START_SCRIPT@"
#define DEFAULT_SHELL   "@DEFAULT_SHELL@"

/* --------- Boolean config variables --------- */

#cmakedefine01 INIT_REPORT_PROC_EXIT
#cmakedefine01 USERAPPS_busybox

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are many dervied constants and convenience constants not
 * designed to be easily changed because of the code makes assumptions about
 * them. Because of that, those constants are hard-coded and not available as
 * CMake variables. With time, some of those constants get "promoted" and moved
 * in CMake, others remain here. See the comments and think about the potential
 * implications before promoting a hard-coded constant to a configurable CMake
 * variable.
 */

#define BUSYBOX         "/initrd/bin/busybox"
#define TTYS0_MINOR     64
