/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once
#include <tilck_gen_headers/config_global.h>

/* ------ Value-based config variables -------- */

#define USER_STACK_PAGES       @USER_STACK_PAGES@

/* --------- Boolean config variables --------- */

#cmakedefine01 FORK_NO_COW
#cmakedefine01 MMAP_NO_COW


/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are many dervied constants and convenience constants like
 * COMPILER_NAME along with some pseudo-constants like USERMODE_VADDR_END not
 * designed to be easily changed because of the code makes assumptions about
 * them. Because of that, those constants are hard-coded and not available as
 * CMake variables. With time, some of those constants get "promoted" and moved
 * in CMake, others remain here. See the comments and think about the potential
 * implications before promoting a hard-coded constant to a configurable CMake
 * variable.
 */


#define USER_VDSO_VADDR  (LINEAR_MAPPING_END)

#define USERMODE_VADDR_END          (BASE_VA) /* biggest user vaddr + 1 */
#define MAX_BRK                  (0x40000000) /* +1 GB (virtual memory) */
#define USER_MMAP_BEGIN               MAX_BRK /* +1 GB (virtual memory) */
#define USER_MMAP_MIN_SZ            (16 * MB)
#define USER_MMAP_MAX_SZ          (1024 * MB)
#define USERMODE_STACK_ALIGN              16u

#define USERMODE_STACK_MAX \
   ((USERMODE_VADDR_END - 1) & ALIGNED_MASK(USERMODE_STACK_ALIGN))
