/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#define KERNEL_FILE_PATH       "/@KERNEL_FATPART_PATH@"
#define KERNEL_FILE_PATH_EFI   "\\@KERNEL_FATPART_PATH_EFI@"

#define SECTOR_SIZE            512

#define BL_ST2_DATA_SEG        @BL_ST2_DATA_SEG@
#define BL_BASE_ADDR           @BL_BASE_ADDR@
#define BL_BASE_SEG            (@BL_BASE_ADDR@ / 16)
#define RAMDISK_SECTOR         @RAMDISK_SECTOR@
#define DISK_UUID              @DISK_UUID@
#define IMGSZ                  @IMGSZ@

