/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

/* ------ Value-based config variables -------- */
#define TIMER_HZ               @TIMER_HZ@

/* --------- Boolean config variables --------- */
#cmakedefine01 KRN_RESCHED_ENABLE_PREEMPT
