/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config file is generated by CMake and stored
 * in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

/* ------ Value-based config variables -------- */
#define MAX_HANDLES            @MAX_HANDLES@

/* --------- Boolean config variables --------- */
#cmakedefine01 KERNEL_BIG_IO_BUF

/*
 * --------------------------------------------------------------------------
 *                  Hard-coded global & derived constants
 * --------------------------------------------------------------------------
 *
 * Here below there are some pseudo-constants not designed to be easily changed
 * because of the code makes assumptions about them. Because of that, those
 * constants are hard-coded and not available as CMake variables. With time,
 * some of those constants get "promoted" and moved in CMake, others remain
 * here. See the comments and think about the potential implications before
 * promoting a hard-coded constant to a configurable CMake variable.
 */

#define USERAPP_MAX_ARGS_COUNT                                 32


/*
 * execve recursion limit with #!/path/to/executable scripts
 * WARNING: cannot be increase without increasing KERNEL_STACK_PAGES.
 */
#define MAX_SCRIPT_REC                                          2

/*
 * Per-task I/O buffer size (pages).
 * Note it is linked with USER_ARGS_PAGE_COUNT.
 *
 * Requirement: IO_COPYBUF_PAGE_COUNT + USER_ARGS_PAGE_COUNT must be
 * a power of 2 smaller than 64.
 */

#if KERNEL_BIG_IO_BUF
   #define IO_COPYBUF_PAGE_COUNT                               63
#else
   #define IO_COPYBUF_PAGE_COUNT                                3
#endif

#define IO_COPYBUF_SIZE       (IO_COPYBUF_PAGE_COUNT * PAGE_SIZE)
#define ARGS_COPYBUF_SIZE      (USER_ARGS_PAGE_COUNT * PAGE_SIZE)

