/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual "config_modules.h" is generated by CMake
 * and put in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#cmakedefine01    MOD_kb8042
#cmakedefine01    MOD_console
#cmakedefine01    MOD_fb
#cmakedefine01    MOD_serial
#cmakedefine01    MOD_debugpanel
#cmakedefine01    MOD_tracing
#cmakedefine01    MOD_sysfs
