/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#cmakedefine01    MOD_kb8042
#cmakedefine01    PS2_DO_SELFTEST
#cmakedefine01    PS2_VERBOSE_DEBUG_LOG
