/* SPDX-License-Identifier: BSD-2-Clause */

/*
 * This is a TEMPLATE. The actual config header file is generated by CMake
 * and put in <BUILD_DIR>/tilck_gen_headers/.
 */

#pragma once

#cmakedefine01    MOD_sysfs

#ifdef KERNEL_TEST
   #define MOD_sysfs_actual 1
#else
   #define MOD_sysfs_actual MOD_sysfs
#endif
