#!/bin/bash

BUILD_DIR="@CMAKE_BINARY_DIR@"
f="@GPT_IMG_FILE@"
tc="@TCROOT@"

if ! [ -d $tc/ovmf ]; then
   echo "In order to boot with EFI, you need to download OVMF first."
   echo "To do that, just run in project's main directory:"
   echo "   ./scripts/build_toolchain -s download_ovmf"
   exit 1
fi

if ! [ -f $f ]; then
   echo "In order to boot with EFI, you need to build the gpt_image target:"
   echo "   make gpt_image"
   exit 1
fi

qemu-system-x86_64 -s @QEMU_RAM_OPT@ \
-bios $tc/ovmf/ovmf-x64/OVMF-pure-efi.fd -drive \
"file=$f,index=0,media=disk,format=raw,cyls=74,heads=16,secs=63" "$@"
