void _isr0() { }
void _isr1() { }
void _isr2() { }
void _isr3() { }
void _isr4() { }
void _isr5() { }
void _isr6() { }
void _isr7() { }
void _isr8() { }
void _isr9() { }
void _isr10() { }
void _isr11() { }
void _isr12() { }
void _isr13() { }
void _isr14() { }
void _isr15() { }
void _isr16() { }
void _isr17() { }
void _isr18() { }
void _isr19() { }
void _isr20() { }
void _isr21() { }
void _isr22() { }
void _isr23() { }
void _isr24() { }
void _isr25() { }
void _isr26() { }
void _isr27() { }
void _isr28() { }
void _isr29() { }
void _isr30() { }
void _isr31() { }
void _isr128() { }

void _irq0() { }
void _irq1() { }
void _irq2() { }
void _irq3() { }
void _irq4() { }
void _irq5() { }
void _irq6() { }
void _irq7() { }
void _irq8() { }
void _irq9() { }
void _irq10() { }
void _irq11() { }
void _irq12() { }
void _irq13() { }
void _irq14() { }
void _irq15() { }

void _idt_load() { }
void _gdt_load() { }
void _tss_flush() { }
void _switch_to_usermode_asm(void *entryPoint, void *stackAddr) { }
