
#pragma once

#define PROJ_BUILD_DIR "@CMAKE_BINARY_DIR@"
#define BUILDTYPE_STR "@CMAKE_BUILD_TYPE@"

#define BL_ST2_DATA_SEG (@BL_ST2_DATA_SEG@)
#define BL_BASE_ADDR (@BL_BASE_ADDR@)
#define CMAKE_KERNEL_BASE_VA (@CMAKE_KERNEL_BASE_VA@)
#define KERNEL_PADDR (@CMAKE_KERNEL_PADDR@)
