#!/bin/bash

# Project's root directory
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_DIR=$MAIN_DIR/..

if [ -z "$CC" ]; then

   CC=gcc

   if which gcc-6 &> /dev/null; then
      CC=gcc-6
   fi

   if which gcc-7 &> /dev/null; then
      CC=gcc-7
   fi
fi

if [ -z "$CXX" ]; then

   CXX=g++

   if which g++-6 &> /dev/null; then
      CXX=g++-6
   fi

   if which g++-7 &> /dev/null; then
      CXX=g++-7
   fi
fi


if ! which $CC &> /dev/null; then
   echo "CC compiler '$CC' not found."
   exit 1
fi

if ! which $CXX &> /dev/null; then
   echo "CXX compiler '$CXX' not found."
   exit 1
fi

if $CC --version | grep gcc &> /dev/null; then

   cc_ver=`$CC --version | head -1 | grep -Eo '[0-9]+[.][0-9][.][0-9]+' | head -1`
   cc_major=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -1`
   cc_minor=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -2 | tail -1`
   echo "[cmake_run] gcc version (parsed): $cc_major.$cc_minor"

   if [ $cc_major -lt 4 ]; then
      echo "Your gcc compiler is too old. Version >= 4.8 is required."
      exit 1
   fi

   if [ $cc_major -eq 4 ] && [ $cc_minor -lt 8 ]; then
      echo "Your gcc compiler is too old. Version >= 4.8 is required."
      exit 1
   fi

fi

if $CXX --version | grep g++ &> /dev/null; then

   cxx_ver=`$CXX --version | head -1 | grep -Eo '[0-9]+[.][0-9][.][0-9]+' | head -1`
   cxx_major=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -1`
   cxx_minor=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -2 | tail -1`
   echo "[cmake_run] g++ version (parsed): $cxx_major.$cxx_minor"

   if [ $cxx_major -lt 4 ]; then
      echo "Your g++ compiler is too old. Version >= 4.8 is required."
      exit 1
   fi

   if [ $cxx_major -eq 4 ] && [ $cxx_minor -lt 8 ]; then
      echo "Your g++ compiler is too old. Version >= 4.8 is required."
      exit 1
   fi

fi

export CC
export CXX

if [ -f $MAIN_DIR/toolchain/cmake/bin/cmake ]; then
   export CMAKE=$MAIN_DIR/toolchain/cmake/bin/cmake
else
   export CMAKE=cmake
fi

export ASM_NASM=$MAIN_DIR/toolchain/nasm/nasm

if [ -n "$RELEASE" ] && [ "$RELEASE" -eq 1 ]; then
   BUILD_TYPE=Release
else
   BUILD_TYPE=Debug
fi

if [ -z "$USE_GCOV" ]; then
   USE_GCOV=off
fi

mkdir -p build
cd build
$CMAKE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -D USE_GCOV:BOOL=$USE_GCOV .. $@

