#!/bin/bash

BUILD_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
f=$BUILD_DIR/gpt_exos.img

qemu-system-x86_64 -s -m 256 \
-bios $BUILD_DIR/../toolchain/ovmf/OVMF-pure-efi.fd -drive \
file=$f,index=0,media=disk,format=raw,cyls=74,heads=16,secs=63 "$@"
