#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

CMAKE_VERSION_TO_DOWNLOAD="$VER_CMAKE"
CMAKE_MIN_VERSION="3.22.0"

function download_cmake_internal {

   show_work_on_component_msg "CMAKE"

   local ver1=$(get_version_comp $CMAKE_VERSION_TO_DOWNLOAD 1)
   local ver2=$(get_version_comp $CMAKE_VERSION_TO_DOWNLOAD 2)
   local ver3=$(get_version_comp $CMAKE_VERSION_TO_DOWNLOAD 3)

   local dirname=cmake-${ver1}.${ver2}.${ver3}-linux-x86_64
   local tarname=$dirname.tar.gz
   local url="https://cmake.org/files/v${ver1}.${ver2}"
   local compdir=$HOST_ARCH_DIR_SYS/cmake/$VER_CMAKE

   mkdir -p $compdir/..
   pushd $compdir/..

   download_file_in_cache "$url" "$tarname"
   extract_cachefile_tar_gz $tarname $dirname $VER_CMAKE

   popd
   CMAKE=$compdir/bin/cmake
}

if [[ $HOST_ARCH == "x86_64" ]]; then
   all_funcs_list+=(download_cmake)
fi

function download_cmake {

   local compdir=$HOST_ARCH_DIR_SYS/cmake/$VER_CMAKE

   if ! [ -d $compdir ]; then

      if ! cmake --version &> /dev/null || [[ "$NO_SYS_CMAKE" == 1 ]]; then

         if [[ "$NO_SYS_CMAKE" == 1 ]] && which cmake &> /dev/null; then
            echo "Note: NO_SYS_CMAKE=1"
         fi

         download_cmake_internal

      else

         # CMake is installed: let's check its version
         local ver=$(generic_get_version_str cmake)
         local major=$(get_version_comp $ver 1)
         local minor=$(get_version_comp $ver 2)

         local min_major=$(get_version_comp $CMAKE_MIN_VERSION 1)
         local min_minor=$(get_version_comp $CMAKE_MIN_VERSION 2)

         if [ $major -lt $min_major ]; then

            # The installed CMake is too old.
            download_cmake_internal

         elif [ $major -eq $min_major ] && [ $minor -lt $min_minor ]; then

            # The installed CMake is too old.
            download_cmake_internal

         else

            # The installed version is >= $CMAKE_MIN_VERSION. Using it.
            CMAKE="cmake"
            echo "NOTE: Using system's CMake (version $major.$minor)"

         fi

      fi

   else
      show_skip_component_msg "CMAKE"
   fi
}

function download_cmake_installed_status {
   if [ -f $HOST_ARCH_DIR_SYS/cmake/$VER_CMAKE/bin/cmake ]; then
      echo "installed"
   elif cmake --version &> /dev/null; then
      echo "skipped"
   fi
}
