#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

function internal_build_dtc {

   echo "Building libfdt from the DTC project... "
   reset_cc_vars

   do_common_cross_compiler_setup
   set_cc_vars_to_tc
   export STATIC_BUILD=1
   export EXTRA_CFLAGS="-fno-stack-protector"

   set +e
   run_command2 "make clean" build.log
   run_command2 "make libfdt V=1 -j$BUILD_PAR" build.log
   dump_cross_compiler_env "build.log"

   if ! [ -f $ARCH_DIR/dtc/$VER_DTC/libfdt/libfdt.a ]; then
      echo "ERROR: build failed: libfdt.a not found !!!" >> build.log
      exit 1
   fi
   set -e

   export STATIC_BUILD=""
   export EXTRA_CFLAGS=""
}

all_funcs_list+=(build_dtc)
function build_dtc {

   local compdir=$ARCH_DIR/dtc/$VER_DTC
   local ver="$VER_DTC"
   local tarname=dtc-$ver.tar.gz
   local url1="https://mirrors.edge.kernel.org/"
   local url2="pub/software/utils/dtc/"

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "DTC"
      mkdir -p $compdir/..
      pushd $compdir/..

      download_file_in_cache $url1$url2 "$tarname"
      extract_cachefile_tar_gz $tarname dtc-$ver $ver

      cd $compdir
      internal_build_dtc

      popd

   elif [ "$REBUILD" == "1" ]; then

      pushd $compdir
      internal_build_dtc
      popd

   else
      show_skip_component_msg "DTC"
   fi
}

function build_dtc_installed_status {

   local arch_list=""

   pushd $ARCH_DIR/..

   for x in ${ALL_ARCH_LIST[@]}; do
      if [ -d $x/dtc/$VER_DTC ]; then
         if [ -f $x/dtc/$VER_DTC/libfdt/libfdt.a ]; then
            arch_list="${arch_list}$x "
         else
            echo "error"
            return
         fi
      fi
   done

   popd

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}
