#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

function download_fbdoom {

   local fbdoom="https://github.com/maximevince/fbDOOM.git"
   local fd_url="https://github.com/freedoom/freedoom/releases/download"
   local ver="$VER_FBDOOM"
   local freedoom="freedoom-$ver"
   local freedoom_zip="$freedoom.zip"
   local tarfile="fbdoom-$ver.tgz"

   if ! [ -f $TC/cache/$tarfile ]; then

      if ! git clone --depth 1 "$fbdoom" $ver; then
         echo "ERROR: unable to clone $fbdoom"
         rm -rf fbDOOM
         exit 1
      fi

      pushd $ver || exit 1

      if ! [ -d fbdoom ]; then
         echo "ERROR: the directory `pwd`/fbdoom does not exist!"
         exit 1
      fi

      pushd fbdoom

      if ! [ -f m_config.c ]; then
         echo "ERROR: cannot file m_config.c"
         exit 1
      fi

      if grep 'homedir = "/mnt"' m_config.c; then
         sed -i 's/homedir = "\/mnt";/homedir = "\/tmp";/g' m_config.c
      else
         echo "WARNING: unable to find the homedir hack in m_config.c"
      fi

      if ! [ -f config.h ]; then
         echo "ERROR: cannot file config.h"
         exit 1
      fi

      if ! grep FILES_DIR config.h &> /dev/null; then
         echo "ERROR: cannot file the FILES_DIR define in config.h!"
         exit 1
      fi

      sed -E -i 's/FILES_DIR .+/FILES_DIR "\/tmp"/g' config.h
      popd

      wget $fd_url/v$ver/$freedoom_zip

      if ! [ -f $freedoom_zip ]; then
         echo "ERROR: unable to download $fd_url/v$ver/$freedoom_zip"
         rm -rf fbDOOM
         exit 1
      fi

      unzip $freedoom_zip || exit 1
      mv $freedoom freedoom || exit 1
      rm $freedoom_zip

      pushd freedoom

      if ! [ -f freedoom1.wad ]; then
         echo "ERROR: unable to find the freedoom1.wad file"
         exit 1
      fi

      gzip freedoom1.wad
      popd
      popd

      tar cfz $tarfile $ver || exit 1
      mv $tarfile $TC/cache
   fi

   extract_cachefile_tar_gz $tarfile $ver $ver
}

if [[ "$ARCH" == "i386" ]]; then
   all_funcs_list+=(build_fbdoom)
fi
function build_fbdoom {

   local compdir=$ARCH_DIR/fbdoom/$VER_FBDOOM

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "FBDOOM"
      reset_cc_vars
      mkdir -p $compdir/..
      pushd $compdir/..

      download_fbdoom
      cd $compdir

      do_common_cross_compiler_setup
      set_cc_vars_to_tc
      export LDFLAGS="-static"

      pushd fbdoom
      set +e
      run_command2 "make NOSDL=1 -j$BUILD_PAR" build.log
      dump_cross_compiler_env "build.log"

      if ! [ -f fbdoom ]; then
         echo "ERROR: build failed !!!" >> build.log
         exit 1
      fi

      set -e
      ${ARCH_GCC_TC}-linux-strip --strip-all fbdoom
      gzip fbdoom
      popd

      export LDFLAGS=""
      popd

   else
      show_skip_component_msg "FBDOOM"
   fi
}

function build_fbdoom_installed_status {

   local arch_list=""
   pushd $ARCH_DIR/..

   for x in ${ALL_ARCH_LIST[@]}; do
      if [ -d $x/fbdoom/$VER_FBDOOM ]; then
         if [ -f $x/fbdoom/$VER_FBDOOM/fbdoom/fbdoom.gz ]; then
            arch_list="${arch_list}$x "
         else
            echo "error"
            return
         fi
      fi
   done

   popd

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}
