#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

##################################
# Build GNU EFI
##################################

# Note: using a gnu-efi's fork on GitHub instead of the official SF repo:
#
#     git://git.code.sf.net/p/gnu-efi/code
#
# exclusively for performance reasons: SF sometimes is too slow for
# CI builds.

function download_gnu_efi {

   local url="https://github.com/vvaltchev/gnu-efi-fork.git"
   local ver="$VER_GNUEFI"
   local tarname="gnu-efi-$ver.tgz"

   download_git_repo_in_cache "$url" $ver $tarname $ver
   extract_cachefile_tar_gz $tarname $ver $ver
}

#
# HACK: patch the GNU-EFI library to force CHAR16 to always be an unsigned
# short, as the L"string" literals when -fshort-wchar is used. That is necessary
# because with the custom cross musl toolchain built for host=aarch64, wchar_t
# is always defined as "int".
#
function gnuefi_patch {

   old="typedef wchar_t CHAR16"
   new="typedef unsigned short CHAR16"

   # Fix definition confusion on riscv64
   old1="typedef uint8_t                 BOOLEAN;"
   new1="typedef char       CHAR8;"

   for x in ia32 x86_64 riscv64; do
      file="inc/${x}/efibind.h"
      if ! [ -f $file ]; then
         echo "ERROR: file $file not found!"
         exit 1
      fi
      run_command "sed -i 's/${old}/${new}/' $file"
      run_command "sed -i 's/${old1}/${new1}/' $file"
   done
}

function build_gnuefi_arch {

   local arch="$1"
   local arch_efi="$2"
   local arch_tc="$3"
   local compdir

   if [[ "$arch" != "noarch" ]]; then
      compdir="$TC/$GCC_TC_VER_/$arch/gnu-efi/$VER_GNUEFI"
   else
      compdir="$TC/noarch/gnu-efi/$VER_GNUEFI"
   fi

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "GNU-EFI (arch: $arch)"
      mkdir -p $compdir/..
      pushd $compdir/..

      download_gnu_efi

      if [[ "$arch" != "noarch" ]]; then

         cd $compdir
         reset_cc_vars
         gnuefi_patch

         local arch_flags="ARCH=${arch_efi} prefix=${arch_tc}-linux-"
         run_command2 "make $arch_flags -j$BUILD_PAR" build_${arch_efi}.log
      fi

      popd

   else
      show_skip_component_msg "GNU-EFI (arch: $arch)"
   fi
}

if [[ "$ARCH" == "i386" || "$ARCH" == "x86_64" ]]; then
   all_funcs_list+=(build_gnuefi)
fi

function build_gnuefi {

   build_gnuefi_arch $ARCH $ARCH_EFI $ARCH_GCC_TC
   build_gnuefi_arch x86_64 x86_64 x86_64
   build_gnuefi_arch noarch noarch noarch
}

function build_gnuefi_installed_status {

   local arch_list=""
   local y

   pushd $ARCH_DIR/..

   for x in ${ALL_ARCH_LIST[@]}; do

      if [ -d $x/gnu-efi/$VER_GNUEFI ]; then

         y="${x}_ARCH_EFI"

         if ! [ -f $x/gnu-efi/$VER_GNUEFI/${!y}/gnuefi/libgnuefi.a ]; then
            echo "error"
            return
         fi
         arch_list="${arch_list}$x "
      fi

   done

   popd

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}

