#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

##############################
# Build gtest
##############################

GTEST_VER="1.12.1"
GTEST_DIRNAME="gtest-$GTEST_VER"
GTEST_SRC_DIR="$TC/noarch/$GTEST_DIRNAME"
GMOCK_DIRNAME="gmock-$GTEST_VER"


function download_googletest {

   local tarname="$GTEST_DIRNAME.tgz"
   local url="https://github.com/google/googletest.git"

   if ! [ -d $GTEST_SRC_DIR ]; then

      download_git_repo_in_cache "$url" release-$GTEST_VER $tarname googletest

      pushd $TC/noarch
      extract_cachefile_tar_gz $tarname "googletest" $GTEST_DIRNAME
      popd
   fi
}

all_funcs_list+=(build_gtest)
function build_gtest {

   download_googletest
   pushd $HOST_ARCH_DIR_SYS

   if ! [ -d $GTEST_DIRNAME ]; then

      show_work_on_component_msg "GOOGLE TEST ($HOST_ARCH)"
      mkdir $GTEST_DIRNAME
      cd $GTEST_DIRNAME

      reset_cc_vars

      $CMAKE                              \
         -DCMAKE_BUILD_TYPE=Debug         \
         -DGOOGLETEST_VERSION=$GTEST_VER  \
         $GTEST_SRC_DIR/googletest

      run_command2 "make -j$BUILD_PAR" build.log

   else
      show_skip_component_msg "GOOGLE TEST ($HOST_ARCH)"
   fi

   popd
}

function build_gtest_installed_status {
   if [ -d $HOST_ARCH_DIR_SYS/$GTEST_DIRNAME ]; then
      if [ -f $HOST_ARCH_DIR_SYS/$GTEST_DIRNAME/lib/libgtest.a ]; then
         echo "installed host_$HOST_ARCH"
      else
         echo "error"
      fi
   fi
}

all_funcs_list+=(build_gmock)
function build_gmock {

   download_googletest
   pushd $HOST_ARCH_DIR_SYS

   if ! [ -d $GMOCK_DIRNAME ]; then

      show_work_on_component_msg "GOOGLE MOCK ($HOST_ARCH)"
      mkdir $GMOCK_DIRNAME
      cd $GMOCK_DIRNAME

      reset_cc_vars

      $CMAKE                              \
         -DCMAKE_BUILD_TYPE=Debug         \
         -DGOOGLETEST_VERSION=$GTEST_VER  \
         $GTEST_SRC_DIR/googlemock

      run_command2 "make -j$BUILD_PAR" build.log

   else
      show_skip_component_msg "GOOGLE MOCK ($HOST_ARCH)"
   fi

   popd
}

function build_gmock_installed_status {
   if [ -d $HOST_ARCH_DIR_SYS/$GMOCK_DIRNAME ]; then
      if [ -f $HOST_ARCH_DIR_SYS/$GMOCK_DIRNAME/lib/libgmock.a ]; then
         echo "installed host_$HOST_ARCH"
      else
         echo "error"
      fi
   fi
}


