#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# LCOV (front end for GCOV)
###############################

function download_lcov {

   local tarname="lcov-${VER_LCOV}.tgz"
   local url="https://github.com/linux-test-project/lcov.git"

   download_git_repo_in_cache "$url" v${VER_LCOV} $tarname lcov-${VER_LCOV}
   extract_cachefile_tar_gz $tarname --
}

all_funcs_list+=(build_lcov)
function build_lcov {

   pushd noarch

   if ! [ -d lcov-${VER_LCOV} ]; then

      show_work_on_component_msg "LCOV"

      if [ -d lcov ]; then

         # Older versions of this script called this package just `lcov`.
         # Rename `lcov` to `lcov-1.13`.

         mv lcov lcov-1.13
         ln -s lcov-1.13 lcov
      fi

      download_lcov
      cd lcov-${VER_LCOV}

   else
      show_skip_component_msg "LCOV"
   fi

   popd
}

function build_lcov_installed_status {
   if [ -d $TC/noarch/lcov-${VER_LCOV} ]; then
      echo "installed noarch"
   fi
}
