#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# LCOV (front end for GCOV)
###############################

LCOV_VER="1.15"

function download_lcov {

   local tarname="lcov-${LCOV_VER}.tgz"
   local url="https://github.com/linux-test-project/lcov.git"

   download_git_repo_in_cache "$url" v${LCOV_VER} $tarname lcov-${LCOV_VER}
   extract_cachefile_tar_gz $tarname --
}

all_funcs_list+=(build_lcov)
function build_lcov {

   pushd noarch

   if ! [ -d lcov-${LCOV_VER} ]; then

      show_work_on_component_msg "LCOV"

      if [ -d lcov ]; then

         # Older versions of this script called this package just `lcov`.
         # Rename `lcov` to `lcov-1.13`.

         mv lcov lcov-1.13
         ln -s lcov-1.13 lcov
      fi

      download_lcov
      cd lcov-${LCOV_VER}

   else
      show_skip_component_msg "LCOV"
   fi

   popd
}
