#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# LCOV (front end for GCOV)
###############################

all_funcs_list+=(build_lcov)
function build_lcov {

   local url="https://github.com/linux-test-project/lcov.git"
   local compdir=$TC/noarch/lcov/$VER_LCOV
   local tarname="lcov-${VER_LCOV}.tgz"
   local tag="v${VER_LCOV}"

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "LCOV"
      mkdir -p $compdir/..
      pushd $compdir/..

      download_git_repo_in_cache "$url" $tag $tarname $VER_LCOV
      extract_cachefile_tar_gz $tarname $VER_LCOV $VER_LCOV

      popd

   else

      show_skip_component_msg "LCOV"
   fi
}

function build_lcov_installed_status {
   if [ -d $TC/noarch/lcov/${VER_LCOV} ]; then
      echo "installed noarch"
   fi
}
