#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

function download_lua {
   local version="$VER_LUA"
   local filename="lua"
   local tarname="lua-$version.tar.gz"
   local url="https://www.lua.org/ftp/"

   download_file_in_cache "$url" "$tarname"
   extract_cachefile_tar_gz $tarname lua-$version $version
}

if [[ "$ARCH" == "i386" || "$ARCH" == "x86_64" ]]; then
   # TODO: check what's the problem with LUA on RISCV64
   all_funcs_list+=(build_lua)
fi
function build_lua {

   local compdir="$ARCH_DIR/lua/$VER_LUA"
   local params=()

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "LUA"
      reset_cc_vars

      mkdir -p $compdir/..
      pushd $compdir/..

      download_lua
      cd $compdir

      do_common_cross_compiler_setup
      set_cc_vars_to_tc

      # Patch Lua's Makefile to remove "-Wl,-E"
      sed -i 's/-Wl,-E//g' src/Makefile

      # Force "linux" as platform in case we're building Tilck on some
      # other OS, like FreeBSD.
      sed -i 's/PLAT= guess/PLAT= linux/g' Makefile

      params+=(CC="$CC")
      params+=(MYCFLAGS="-std=gnu99")
      params+=(AR=\"$AR rcu\")
      params+=(RANLIB="$RANLIB")

      run_command2 "make ${params[*]}" build.log

      popd

   else
      show_skip_component_msg "LUA"
   fi

   reset_cc_vars
}

function build_lua_installed_status {

   local arch_list=""

   pushd $ARCH_DIR/..

   for x in ${ALL_ARCH_LIST[@]}; do
      if [ -d $x/lua/$VER_LUA ]; then
         if [ -f $x/lua/$VER_LUA/src/lua ]; then
            arch_list="${arch_list}$x "
         else
            echo "error"
            return
         fi
      fi
   done

   popd

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}
