#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# Mtools
###############################

all_funcs_list+=(build_mtools)
function build_mtools {

   pushd $HOST_ARCH_DIR_SYS

   if ! [ -d mtools ]; then

      show_work_on_component_msg "MTOOLS"
      local pkgname="mtools-$VER_MTOOLS"
      local tarname=$pkgname.tar.gz

      download_file_in_cache "ftp://ftp.gnu.org/gnu/mtools" "$tarname"
      extract_cachefile_tar_gz $tarname $pkgname mtools

      cd mtools
      reset_cc_vars

      run_command2 ./configure configure.log
      run_command2 "make -j$BUILD_PAR" build.log
   else
      show_skip_component_msg "MTOOLS"
   fi

   popd
}

function build_mtools_installed_status {
   if [ -d $HOST_ARCH_DIR_SYS/mtools ]; then
      if [ -f $HOST_ARCH_DIR_SYS/mtools/mtools ]; then
         echo "installed host_${HOST_ARCH}"
      else
         echo "error"
      fi
   fi
}
