#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

###############################
# Mtools
###############################

all_funcs_list+=(build_mtools)
function build_mtools {

   local compdir=$HOST_ARCH_DIR_SYS/mtools/$VER_MTOOLS
   local pkgname="mtools-$VER_MTOOLS"
   local tarname=$pkgname.tar.gz

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "MTOOLS"
      mkdir -p $compdir/..
      pushd $compdir/..

      download_file_in_cache "https://ftp.gnu.org/gnu/mtools" "$tarname"
      extract_cachefile_tar_gz $tarname $pkgname $VER_MTOOLS

      cd $VER_MTOOLS
      reset_cc_vars

      if [[ "$OS" == "FreeBSD" ]]; then
         local MTOOLS_LIBS="LIBS=-liconv"
      fi

      run_command2 "./configure $MTOOLS_LIBS" configure.log
      run_command2 "make -j$BUILD_PAR" build.log
      popd

   else
      show_skip_component_msg "MTOOLS"
   fi
}

function build_mtools_installed_status {

   local compdir=$HOST_ARCH_DIR_SYS/mtools/$VER_MTOOLS

   if [ -d $compdir ]; then
      if [ -f $compdir/mtools ]; then
         echo "installed host_${HOST_ARCH}"
      else
         echo "error"
      fi
   fi
}

