#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

all_funcs_list+=(download_libmusl)

function download_libmusl {

   local ver="$VER_MUSL"
   local tarname="libmusl-$ver.tgz"
   local url="git://git.musl-libc.org/musl"

   pushd noarch

   if ! [ -d musl ]; then
      show_work_on_component_msg "LIBMUSL"
      download_git_repo_in_cache "$url" v$ver $tarname musl
      extract_cachefile_tar_gz $tarname --
   else
      show_skip_component_msg "LIBMUSL"
   fi

   popd
}

function download_libmusl_installed_status {

   if [ -d $TC/noarch/musl ]; then
      echo "installed noarch"
   fi
}
