#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

all_funcs_list+=(build_ncurses)
function build_ncurses {

   local ver="$VER_NCURSES"
   local tarname=ncurses-$ver.tar.gz
   local compdir=$ARCH_DIR/ncurses/$ver
   local install_dir=$compdir/install
   local params=()

   if ! [ -d $compdir ]; then

      show_work_on_component_msg "NCURSES"
      reset_cc_vars

      mkdir -p $compdir/..
      pushd $compdir/..

      download_file_in_cache "https://ftp.gnu.org/pub/gnu/ncurses" "$tarname"
      extract_cachefile_tar_gz $tarname ncurses-$ver $ver

      mkdir -p $install_dir
      cd $compdir

      params+=(--host=${ARCH_SHORT}-pc-linux-gnu)
      params+=(--prefix=$install_dir)
      params+=(--datarootdir=/usr/share)
      params+=(--disable-db-install)
      params+=(--without-progs)
      params+=(--without-cxx)
      params+=(--without-cxx-binding)
      params+=(--without-ada)
      params+=(--without-manpages)
      params+=(--without-dlsym)

      do_common_cross_compiler_setup
      set_cc_vars_to_tc
      run_command2 "./configure ${params[*]}" configure.log

      set +e
      run_command2 "make -j$BUILD_PAR" build.log
      run_command2 "make install" install.log
      dump_cross_compiler_env "build.log"

      if ! [ -f $install_dir/lib/libncurses.a ]; then
         echo "ERROR: build failed !!!" >> build.log
         exit 1
      fi

      set -e
      export CC_POST_FLAGS=""
      popd

   else
      show_skip_component_msg "NCURSES"
   fi
}

function build_ncurses_installed_status {

   local ver="$VER_NCURSES"
   local arch_list=""
   pushd $ARCH_DIR/..

   for x in ${ALL_ARCH_LIST[@]}; do
      if [ -d $x/ncurses/$ver ]; then
         if [ -f $x/ncurses/$ver/install/lib/libncurses.a ]; then
            arch_list="${arch_list}$x "
         else
            echo "error"
            return
         fi
      fi
   done

   popd

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}
