#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

if [[ "$ARCH" == "i386" ]]; then
   all_funcs_list+=(build_tfblib)
fi
function build_tfblib {

   local dest="$MAIN_DIR/userapps/extra/tfblib"
   local url="https://github.com/vvaltchev/tfblib"
   local tarname="tfblib-$VER_TFBLIB.tgz"
   local compdir="$TC/noarch/tfblib/$VER_TFBLIB"

   if ! [ -d $compdir ]; then

      mkdir -p $compdir
      pushd $compdir/..

      show_work_on_component_msg "TFBLIB"
      download_git_repo_in_cache "$url" $VER_TFBLIB $tarname $VER_TFBLIB
      extract_cachefile_tar_gz $tarname $VER_TFBLIB $VER_TFBLIB

      if [ -L $dest ]; then
         rm -f $dest
      fi

      ln -s $compdir $dest
      popd

   else
      show_skip_component_msg "TFBLIB"
   fi
}

function build_tfblib_installed_status {

   local compdir="$TC/noarch/tfblib/$VER_TFBLIB"

   if [ -d $TC/noarch/tfblib ]; then
      echo "installed noarch"
   fi
}
