#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

TFBLIB_VER="latest"

if [[ "$ARCH" == "i386" ]]; then
   all_funcs_list+=(build_tfblib)
fi
function build_tfblib {

   local dest

   if [ ! -d noarch/tfblib ]; then

      pushd noarch
      show_work_on_component_msg "TFBLIB"
      git clone https://github.com/vvaltchev/tfblib
      dest="$MAIN_DIR/userapps/extra/tfblib"
      if [ -L "$dest" ]; then
         rm -f "$dest"
      fi
      ln -s $TC/noarch/tfblib "$dest"
      popd

   else
      show_skip_component_msg "TFBLIB"
   fi
}

function build_tfblib_installed_status {
   if [ -d $TC/noarch/tfblib ]; then
      echo "installed noarch"
   fi
}
