#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

# This is the latest version of vim that works correctly. Version > v8.2.5057
# uses unsupported kernel features related to timers.
#
# See https://github.com/vim/vim/issues/10647
#
# TODO: check what exactly needs to be implemented in Tilck to support the
# latest version of vim and consider if it's worth the effort for Tilck in
# general. Hint: it looks like implementing sys_getitimer() and sys_setitimer()
# might be enough.

VIM_VER="v8.2.5056"

function download_vim {

   local tarname="vim-$VIM_VER.tgz"
   local url="https://github.com/vim/vim.git"
   local tag=""

   if [[ "$VIM_VER" != "latest" ]]; then
      tag="$VIM_VER"
   fi

   download_git_repo_in_cache "$url" "$tag" $tarname vim
   extract_cachefile_tar_gz $tarname --
}

if [[ "$ARCH" == "i386" ]]; then
   all_funcs_list+=(build_vim)
fi
function build_vim {

   pushd $ARCH

   if ! [ -d vim ]; then

      show_work_on_component_msg "VIM"
      reset_cc_vars
      local ncurses="$TC/$ARCH/ncurses/install"

      if ! [ -d "$ncurses" ]; then
         echo "ERROR: ncurses is needed to build vim"
         echo "How to fix: run this script with -s build_ncurses first"
         exit 1
      fi

      download_vim
      cd vim

      local curr="$PWD"

      do_common_cross_compiler_setup
      set_cc_vars_to_tc
      export CFLAGS="-ggdb -Os"
      export LDFLAGS="-static -L$ncurses/lib -lncurses"
      export CPPFLAGS="-I$ncurses/include -I$ncurses/include/ncurses"

      local opts=""
      opts="$opts --prefix=$curr/install"
      opts="$opts --build=${HOST_ARCH}-linux-gnu"
      opts="$opts --host=${ARCH_GCC_TC}-linux-musl"
      opts="$opts --target=${ARCH_GCC_TC}-linux-musl"
      opts="$opts --with-features=normal"
      opts="$opts --with-tlib=ncurses"
      opts="$opts vim_cv_toupper_broken=no"
      opts="$opts vim_cv_terminfo=yes"
      opts="$opts vim_cv_tgetent=zero"
      opts="$opts vim_cv_getcwd_broken=no"
      opts="$opts vim_cv_stat_ignores_slash=no"
      opts="$opts vim_cv_memmove_handles_overlap=yes"

      set +e
      run_command2 "./configure $opts" configure.log
      run_command2 "make -j$BUILD_PAR" build.log
      run_command2 "make install" install.log
      set -e

      dump_cross_compiler_env "build.log"

      if ! [ -f install/bin/vim ]; then
         echo "ERROR: build failed !!!" >> build.log
         exit 1
      fi

      pushd install

         cp -r ../runtime .

         pushd runtime
            rm -rf doc lang tutor spell
         popd

         tar cfz vr.tgz runtime
         rm -rf runtime

         gzip -c --best ./bin/vim > vim.gz
         chmod 644 vim.gz
      popd

      if ! [ -f $TC/$ARCH/vim/install/vim.gz ]; then
         echo "ERROR: the install failed !!!" >> install.log
         exit 1
      fi

      export CFLAGS=""
      export LDFLAGS=""
      export CPPFLAGS=""

   else
      show_skip_component_msg "VIM"
   fi

   reset_cc_vars
   popd
}

function build_vim_installed_status {

   local arch_list=""

   for x in $ALL_ARCH_LIST; do
      if [ -d $TC/$x/vim ]; then
         if [ -f $TC/$x/vim/install/vim.gz ]; then
            arch_list="${arch_list}$x "
         else
            echo "error"
            return
         fi
      fi
   done

   # Drop the trailing " "
   if [[ "${arch_list: -1}" == " " ]]; then
      arch_list="${arch_list:: -1}"
   fi

   if [ -n "$arch_list" ]; then
      echo "installed $arch_list"
   fi
}
