#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

function download_zlib {

   local tarname="zlib-1.2.11.tgz"
   local url="https://github.com/madler/zlib"

   download_git_repo_in_cache "$url" v1.2.11 $tarname zlib
   extract_cachefile_tar_gz $tarname --
}

all_funcs_list+=(build_zlib)
function build_zlib {

   pushd $ARCH

   if ! [ -d zlib ]; then

      show_work_on_component_msg "ZLIB"
      reset_cc_vars

      download_zlib
      cd zlib

      local p="$TC/$ARCH/zlib/install"

      if [[ "$HOST_ARCH" != "$BUILD_ARCH" ]]; then

         # Case HOST_ARCH == ARCH
         # Note: if HOST_ARCH not in [BUILD_ARCH, ARCH], we fail earlier.
         export SYS_CC="$CC"
         export SYS_CXX="$CXX"
         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"

      else

         # Default case
         export CROSS_PREFIX="${ARCH_GCC_TC}-linux-"
         set_cc_vars_to_tc
      fi

      run_command2 "./configure --prefix='$p' --static" configure.log
      run_command2 "make -j$BUILD_PAR" build.log
      run_command2 "make install" install.log
      export CROSS_PREFIX=""

   else
      show_skip_component_msg "ZLIB"
   fi

   popd
}
