#!/bin/bash

if [[ "$LOGLEVEL" == "" ]]; then
   LOGLEVEL="error"
fi

exec clangd \
   --tweaks=-DefineInline,-SwapBinaryOperands \
   --query-driver=**/*-linux-gcc,**/*-linux-g++ \
   --enable-config \
   --log=$LOGLEVEL \
   --check="$1" 2>&1
