#!/bin/bash

# Project's root directory
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_DIR="$(cd "$SOURCE_DIR/../.." && pwd)"
CMDS=$MAIN_DIR/build/compile_commands.json

if ! [ -f $CMDS ]; then
   echo "ERROR: compile_commands.json not found"
   exit 1
fi

if ! [ -f $SOURCE_DIR/clangd-check-single-file ]; then
   echo "ERROR: clangd-check-single-file not found"
   exit 1
fi

cd $MAIN_DIR
files_list=()

while IFS= read -r file; do
   files_list+=("$file")
done < <(fd '\.c\.h')

while IFS= read -r file; do
   files_list+=("$file")
done < <(jq -r '.[].file' $CMDS | grep -E '\.(c|cc|cxx|cpp)$')


i=0
failed=0
count=${#files_list[@]}

for file in "${files_list[@]}"; do
   if [[ $file == */tfblib/fonts/*.c ]]; then
      # Font files encoded in C files take a long time to be processed by
      # clangd, let's skip them.
      continue
   fi
   echo "[$((i*100/count))%] FILE: $file"
   if ! out=$($SOURCE_DIR/clangd-check-single-file $file); then
      echo "------------------------------------------------------------------"
      echo "$out"
      echo "------------------------------------------------------------------"
      failed=$((failed+1))
   fi
   i=$((i+1))
done
echo "[100%] DONE"

if [[ $failed -gt 0 ]]; then
   exit 1
fi
