#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause

if ! [ -d kernel ] || ! [ -d userapps ] || ! [ -f LICENSE ]; then
   echo "You need to run this script from project's root directory"
   exit 1
fi

echo "Running CTAGS..."

ctags --languages=C,C++,Python -R                  \
   config/ common/ kernel/ include/ modules/       \
   tests/ boot/ userapps/ scripts/build_apps/

if ! [ -f tags ]; then
   echo "ERROR: File 'tags' NOT found"
   exit 1
fi

echo "DONE"
