#!/usr/bin/env bash

pkg="$1"
ci=

if [ "$1" == "-ci" ]; then
   pkg="$2"
   ci=1
fi

if ! dnf list installed $pkg &> /dev/null; then

   echo "We need to install the package $pkg"

   if [ "$ci" == 1 ]; then
      cmd="dnf install -y $pkg"
   else
      cmd="sudo dnf install $pkg"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

