#!/usr/bin/env bash

if ! dnf list installed $1 &> /dev/null; then

   echo "We need to install the package $1"

   if [ "$RUNNING_IN_CI" == 1 ]; then
      cmd="dnf install -y $1"
   else
      cmd="sudo dnf install $1"
   fi

   echo "Running the command: $cmd"
   eval $cmd
fi

