#!/usr/bin/env bash

pkg="$1"
ci=

if [ "$1" == "-ci" ]; then
   pkg="$2"
   ci=1
fi

if [ "$ci" == 1 ]; then
   cmd="dnf makecache"
else
   cmd="sudo dnf makecache"
fi

echo "Running the command: $cmd"
eval $cmd

